### DISCUSSION TITLE
TinyTds - Adaptive Server connection timed out

### DISCUSSION THREAD

**Discussion by yozart** [docker-library/redmine#341] [General]
Hello Guys,

I'm facing issues with search features that throws 500 Internal error quiet often. I'm connected to a SQL server installed on an external machine.

> I, [2024-09-19T12:09:29.762648 #129]  INFO -- : Started GET "/projects/it14/search?utf8=%E2%9C%93&scope=&issues=1&q=pr%C3%A9l%C3%A8vement" for 10.148.5.14 at 2024-09-19 12:09:29 +0000
> I, [2024-09-19T12:09:29.764138 #129]  INFO -- : Processing by SearchController#index as HTML
> I, [2024-09-19T12:09:29.764305 #129]  INFO -- :   Parameters: {"utf8"=>"✓", "scope"=>"", "issues"=>"1", "q"=>"prélèvement", "id"=>"it14"}
> I, [2024-09-19T12:09:29.777268 #129]  INFO -- :   Current user: yozart (id=6)
> I, [2024-09-19T12:09:35.608093 #129]  INFO -- : Completed 500 Internal Server Error in 5844ms (ActiveRecord: 5821.0ms | Allocations: 6746)
> F, [2024-09-19T12:09:35.610621 #129] FATAL -- :   ActiveRecord::StatementTimeout (TinyTds::Error: Adaptive Server connection timed out):

I tried to add  REDMINE_DB_TIMEOUT: 60 in my docker compose without success.

Any idea what I shall do to avoid such issue ?

my docker compose :
```yaml
  redmine:
    image: redmine:5.1.3
    container_name: redmine
    restart: always
    environment:
      REDMINE_DB_ADAPTER: "sqlserver"
      REDMINE_DB_DATABASE: "REDMINE"
      REDMINE_DB_SQLSERVER: "my sql server ip"
      REDMINE_DB_PORT: "1433"
      REDMINE_DB_USERNAME: "user"
      REDMINE_DB_PASSWORD: "password"
      REDMINE_PLUGINS_MIGRATE: true
      REDMINE_DB_TIMEOUT: 60
    ports:
      - "3000:3000"
    volumes:
      - REDMINE_DATA:/usr/src/redmine/files
      - REDMINE_PLUGINS:/usr/src/redmine/plugins
      - /var/lib/docker/volumes/REDMINE_CONF/configuration.yml:/usr/src/redmine/config/configuration.yml
    networks:
      - common_network
    entrypoint: ["sh", "-c", "chmod -R o-w \"$$GEM_HOME/gems\" && chmod -R o-w \"$$GEM_HOME/extensions\" && apt-get update && apt-get install -y shared-mime-info && /docker-entrypoint.sh rails server -b 0.0.0.0"]
```

PS: SQL Server version is 2019
