### DISCUSSION TITLE
Unable to load assets when using sub-uri

### DISCUSSION THREAD

**Discussion by Badwolf369** [docker-library/redmine#371] [General]
I have set up my redmine instance to try and use nginx as the reverse proxy, but for some reason it is incapable of loading in the js and css files. I have tried so many different things, but most solutions focus on prepending the asset call with "/redmine", they don't count on that URI also 404ing.
Here is my environment.rb file
```ruby
# frozen_string_literal: true

# Load the Rails application
require File.expand_path('../application', __FILE__)

# Make sure there's no plugin in vendor/plugin before starting
vendor_plugins_dir = File.join(Rails.root, "vendor", "plugins")
if Dir.glob(File.join(vendor_plugins_dir, "*")).any?
  $stderr.puts "Plugins in vendor/plugins (#{vendor_plugins_dir}) are no longer allowed. " \
    "Please, put your Redmine plugins in the `plugins` directory at the root of your " \
    "Redmine directory (#{File.join(Rails.root, "plugins")})"
  exit 1
end

# Initialize the Rails application
RedmineApp::Application.routes.default_scope = "/redmine"
RedmineApp::Application.initialize!

Redmine::Utils::relative_url_root = "/redmine"
```
Here is my nginx config
```
location /redmine {
    proxy_pass http://redmine_app:3000;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
}
```
And here is my docker compose
```yml
  redmine_app:
    container_name: redmine_app
    image: redmine:latest
    depends_on:
      - redmine_db
    networks:
      - issue_network
      - redmine_network
    ports:
      - 2320:3000
    volumes:
      - S:/media-server/issues/redmine/usr/src/redmine/files:/usr/src/redmine/files
      - S:/media-server/issues/redmine/usr/src/redmine/config/environment.rb:/usr/src/redmine/config/environment.rb
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
    restart: unless-stopped

  redmine_db:
    container_name: redmine_db
    image: mariadb:latest
    networks:
      - redmine_network
    volumes:
      - S:/media-server/issues/redmine-mariadb/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: [REDACTED]
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    restart: unless-stopped
```
I can see in the logs that the proper URI is being grabbed, but for some reason it still 404's on all assets. Interestingly, It does not 404 on any of the app's pages. They all load just fine.

![Image](https://github.com/user-attachments/assets/bf77b05d-3cd7-40fe-a5e4-6341f9bf0f67)

![Image](https://github.com/user-attachments/assets/3b23d494-6f4a-42a8-a407-25687642d099)
