### ISSUE TITLE
Cannot mount host redmine code to do development?

### ISSUE THREAD

**Issue by zjsxwc** [docker-library/redmine#125]
hi,  i want to mount host redmine code to do development, but it seems not work.

here is my docker-compose.yml:  

```
  redmine:
    image: redmine:3.4.3-passenger
    depends_on:
      - mysql
    ports:
      - 80:3000
    volumes:
      - /data/redmine:/usr/src/redmine     #<-- here, I use my host directory ` /data/redmine` to do development
```

what's the best way to develop redmine through docker?
