### ISSUE TITLE
Multiple index.html.xxx files generated in docker container

### ISSUE THREAD

**Issue by pskillen** [docker-library/redmine#129]
**Summary**
After running Redmine for a few seconds, extra `index.html.xx` files appear in the container's `/usr/src/redmine/` directory. These continue to appear (with an incrementing file number) until the server can't function any more (~200k files).

I can't be certain if these are related to page requests as this is in a production environment, but they don't seem related.

Note in `ls` output below that files are owned by `root:root`, but all other files in directory are `redmine:redmine`. I've chowned the real index.html to `redmine:redmine` but it had no effect.

**Environment**
* Running `redmine:3.4.4` (although I think it also applies to `redmine:3.4.6`)
* Postgres DB (not dockerised)
* Installed Redmine DMSF plugin

**Files**
```
drwxrwxr-x 1 redmine redmine 4.0K Jan  8  2018 doc
drwxrwxr-x 1 redmine redmine 4.0K Jan  8  2018 extra
drwxr-xr-x 4 redmine redmine 4.0K Jun 26 19:46 files
-rw-r--r-- 1 redmine redmine 3.3K Jun 26 14:22 index.html
-rw-r--r-- 1 root    root    4.7K Oct  3 08:17 index.html.1
-rw-r--r-- 1 root    root    4.7K Oct  3 08:17 index.html.2
-rw-r--r-- 1 root    root    4.7K Oct  3 08:18 index.html.3
-rw-r--r-- 1 root    root    4.7K Oct  3 08:18 index.html.4
-rw-r--r-- 1 root    root    4.7K Oct  3 08:19 index.html.5
-rw-r--r-- 1 root    root    4.7K Oct  3 08:19 index.html.6
-rw-r--r-- 1 root    root    4.7K Oct  3 08:20 index.html.7
drwxrwxr-x 1 redmine redmine 4.0K Jan  8  2018 lib
drwxr-xr-x 1 redmine redmine 4.0K Jun 26 14:14 log
```
**After a couple of days**
```
root@[container]:/usr/src/redmine# ls
...
index.html.11119	 index.html.12262  index.html.13405  index.html.2006   index.html.315	index.html.4293  index.html.5436  index.html.658   index.html.7722  index.html.8866
index.html.1112		 index.html.12263  index.html.13406  index.html.2007   index.html.3150	index.html.4294  index.html.5437  index.html.6580  index.html.7723  index.html.8867
index.html.11120	 index.html.12264  index.html.13407  index.html.2008   index.html.3151	index.html.4295  index.html.5438  index.html.6581  index.html.7724  index.html.8868
index.html.11121	 index.html.12265  index.html.13408  index.html.2009   index.html.3152	index.html.4296  index.html.5439  index.html.6582  index.html.7725  index.html.8869
index.html.11122	 index.html.12266  index.html.13409  index.html.201    index.html.3153	index.html.4297  index.html.544   index.html.6583  index.html.7726  index.html.887
root@[container]:/usr/src/redmine# rm index.html.*
root@[container]:/usr/src/redmine# ls
CONTRIBUTING.md  Gemfile.lock	      Gemfile.lock.postgresql  Gemfile.lock.sqlserver  Rakefile  appveyor.yml  config	  db   extra  index.html  log	   public  test  vendor
Gemfile		 Gemfile.lock.mysql2  Gemfile.lock.sqlite3     README.rdoc	       app	 bin	       config.ru  doc  files  lib	  plugins  script  tmp
root@[container]:/usr/src/redmine# 
```

**Comment by wglambert** [comment]
Can you give all the commands you ran for reproducing the issue

**Comment by pskillen** [comment]
I'm running via a docker-compose file:

```
---
version: '3.0'

services:
  server:
    image: redmine:3
    environment:
      - REDMINE_DB_POSTGRES=[server]
      - REDMINE_DB_USERNAME=[user]
      - REDMINE_DB_PASSWORD=[password]
      - REDMINE_DB_DATABASE=[db]
    ports:
      - 0.0.0.0:8084:3000/tcp
    volumes:
      - /opt/redmine/server/files:/usr/src/redmine/files
      - /opt/redmine/server/plugins:/usr/src/redmine/plugins
      - /opt/redmine/server/themes:/usr/src/redmine/public/themes
      - /opt/redmine/server/data:/redminedata
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-o", "/dev/null", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
```
