### ISSUE TITLE
Warnings about passenger_native_support

### ISSUE THREAD

**Issue by serpi90** [docker-library/redmine#134]
User does not have  enough privileges to compile, download locations are not valid. https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz does not exist, but 2.4.4 does

```
redmine_redmine.1.l8pa3ra0w66j@PC51    | The Gemfile's dependencies are satisfied
redmine_redmine.1.l8pa3ra0w66j@PC51    |  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
redmine_redmine.1.l8pa3ra0w66j@PC51    |      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
redmine_redmine.1.l8pa3ra0w66j@PC51    |      Warning: compilation didn't succeed. To learn why, read this file:
redmine_redmine.1.l8pa3ra0w66j@PC51    |      /tmp/passenger_native_support-snq30c.log
redmine_redmine.1.l8pa3ra0w66j@PC51    |  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
redmine_redmine.1.l8pa3ra0w66j@PC51    |      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
redmine_redmine.1.l8pa3ra0w66j@PC51    |      Could not download https://github.com/phusion/passenger/releases/download/release-5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz: 2018-10-30 18:05:01 ERROR 404: Not Found.
redmine_redmine.1.l8pa3ra0w66j@PC51    |      Trying next mirror...
redmine_redmine.1.l8pa3ra0w66j@PC51    |      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz: 2018-10-30 18:05:05 ERROR 404: Not Found.
redmine_redmine.1.l8pa3ra0w66j@PC51    |      Trying next mirror...
redmine_redmine.1.l8pa3ra0w66j@PC51    |      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.3.5/rubyext-ruby-2.4.5-x86_64-linux.tar.gz: 2018-10-30 18:05:06 ERROR 403: Forbidden.
redmine_redmine.1.l8pa3ra0w66j@PC51    |  [passenger_native_support.so] will not be used (can't compile or download) 
```
`cat passenger_native_support-8fch7x.log`
```
# current user is: redmine
# mkdir -p /usr/local/bundle/gems/passenger-5.3.5/buildout/ruby/ruby-2.4.5-x86_64-linux
Encountered permission error, trying a different directory...
-------------------------------
# mkdir -p /home/redmine/.passenger/native_support/5.3.5/ruby-2.4.5-x86_64-linux
Encountered permission error, but no more directories to try. Giving up.
```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by serpi90** [comment]
docker-compose.yml:
```yaml
version: "3.1"
services:
  redmine:
    image: redmine:3.4.6-passenger
    depends_on:
      - db
    ports:
      - "8080:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```
on a docker swarm run `docker stack deploy --compose-file docker-compose.yml redmine`
I assume the equivalent command on docker-compose is `docker-compose up`
