### ISSUE TITLE
3.4.6 docker image write permission error.

### ISSUE THREAD

**Issue by vietthang207** [docker-library/redmine#137]
Hi all. I'd like to report a bug for docker image tag 3.4.6. I think it was pushed on Friday Nov 9th or Satturday Nov 10th.

This is the system log:
```
Nov 12 01:02:10 prod-redmine-server redmine7198: `/home/redmine` is not a directory.
Nov 12 01:02:10 prod-redmine-server redmine7198: Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Nov 12 01:02:10 prod-redmine-server redmine7198: Bundler can't satisfy your Gemfile's dependencies.
Nov 12 01:02:10 prod-redmine-server redmine7198: Install missing gems with `bundle install`.
Nov 12 01:02:10 prod-redmine-server redmine7198: `/home/redmine` is not a directory.
Nov 12 01:02:10 prod-redmine-server redmine7198: Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Nov 12 01:02:10 prod-redmine-server redmine7198: There was an error while trying to write to `/usr/local/bundle/config`. It is
Nov 12 01:02:10 prod-redmine-server redmine7198: likely that you need to grant write permissions for that path.
```

I think it is because redmine is trying to edit `/usr/local/bundler/config`, but the permission is `0644`, and the owner is `root`, group id is `staff`.

Thanks in advance!

**Comment by popovpo** [comment]
I have similar problem, but if i load locally saved before on disk - all fine. It seems that last updates raise errors.

**Comment by vietthang207** [comment]
@popovpo Me too, It only happened on my production server and I can't reproduce on another VM. I tried to dump the database and include all datafile, but this works just fine on a brand new installation.

**Comment by ricardoapaes** [comment]
Here is also happening, do we have any solution?

**Comment by vietthang207** [comment]
It probably due to this plugin. https://github.com/scrum2b/scrum2b

**Comment by citiscaner** [comment]
Same issue i am facing with a fresh rebuild services.

**Comment by f466162** [comment]
Same problem here with the same error message in the logs. Can I provide any additional information to dig into the problem?

**Comment by tianon** [comment]
It would be really helpful to have a way to reproduce so we can debug
what's going on.

**Comment by f466162** [comment]
Ok, I will try my best ;-)

The Docker version used is: Docker version 18.06.1-ce, build e68fc7a

I use the Redmine 3.4 image in a Docker Compose setup:

```
  redmine:
    image: redmine:3.4
    restart: 'no'
    hostname: 'redmine.local'
    environment:
      REDMINE_DB_POSTGRES: xxx
      REDMINE_DB_DATABASE: xxx
      REDMINE_DB_USERNAME: xxx
      REDMINE_DB_PASSWORD: xxx
      REDMINE_PLUGINS_MIGRATE: 1
    links:
      - pgsql:database
    depends_on:
      - pgsql
    volumes:
      - '/xxx/redmine_configuration.yml:/usr/src/redmine/config/configuration.yml'
      - '/xxx/redmine_files:/usr/src/redmine/files'
      - '/xxx/redmine_plugins:/usr/src/redmine/plugins'
      - '/xxx/redmine_home:/home/redmine'
    mem_limit: 512M
```
As you can see I already added /home/redmine as a volume. I did a chown nobody and one permission error is gone (see log below).

The plugins folder contains three plugins:

- redmine_ldap_sync  
- redmine_pretend  
- redmine_xlsx_format_issue_exporter

The log shows up the following:

```
Nov 14 20:46:22 sys redmine:3.4[1093]: Bundler can't satisfy your Gemfile's dependencies.
Nov 14 20:46:22 sys redmine:3.4[1093]: Install missing gems with `bundle install`.
Nov 14 20:46:23 sys redmine:3.4[1093]: There was an error while trying to write to `/usr/local/bundle/config`. It is
Nov 14 20:46:23 sys redmine:3.4[1093]: likely that you need to grant write permissions for that path.
```

The image is pulled on a daily base from hub.docker.com and unmodified. 

If you need any additional information, let me know.

**Comment by tianon** [comment]
I've got a first pass for at least the home directory related issues at https://github.com/docker-library/redmine/pull/141 that could definitely use some testing. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/redmine/pull/141 fixed the `/home/redmine` bits of this issue, but I'm reopening to track the weirdness around `/usr/local/bundle/config` that we haven't been able to reproduce reliably yet to even start to debug what's going on there.

**Comment by Silex** [comment]
This looks pretty straightforward: the user redmine cannot write to `/usr/local/bundle/config`.

``` 
$ docker-compose run --rm web bash
redmine@c513fd2ce928:/usr/src/redmine$ bash -x /docker-entrypoint.sh passenger start
+ set -Eeo pipefail
+ isLikelyRedmine=
+ case "$1" in
+ isLikelyRedmine=1
+ '[' -n 1 ']'
++ id -u
+ '[' 999 = 0 ']'
+ '[' -n 1 ']'
+ _fix_permissions
++ id -u
+ '[' 999 = 0 ']'
+ find config files log public/plugin_assets tmp -type d '!' -perm 755 -exec chmod 755 '{}' +
+ find config files log public/plugin_assets tmp -type f '!' -perm 644 -exec chmod 644 '{}' +
+ '[' '!' -f ./config/database.yml ']'
++ ruby -e '
			require '\''yaml'\''
			conf = YAML.load_file('\''./config/database.yml'\'')
			puts conf['\''production'\'']['\''adapter'\'']
		'
+ adapter=mysql2
+ cp Gemfile.lock.mysql2 Gemfile.lock
+ bundle check
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
+ bundle install --without development test
There was an error while trying to write to `/usr/local/bundle/config`. It is likely that you need to grant write permissions for that path.
```

**Comment by Silex** [comment]
Found the fix!

``` bash
unset BUNDLE_APP_CONFIG 
unset BUNDLE_PATH
```

Not sure where to apply it tho.

**Comment by Silex** [comment]
Also I see this:

``` shell
root@92f9cb45f073:/usr/src/redmine# ls -alh /home/redmine/
total 12K
drwxrwxrwt 1 redmine redmine 4.0K Nov 20 10:18 .
drwxr-xr-x 1 root    root    4.0K Nov 20 10:17 ..
drwxr-xr-x 3 root    root    4.0K Nov 20 10:18 .bundle
```

The directory `.bundle` being owned by root cannot be a good thing no?

**Comment by tianon** [comment]
Thanks for the digging!  I've finally managed to reproduce with the following simple steps thanks to your additional clues:

```console
$ mkdir oh-no
$ echo "gem 'l'" > oh-no/Gemfile
$ docker run -it --rm -v "$PWD/oh-no":/usr/src/redmine/plugins/oh-no:ro redmine:3.4
```

(Which fails immediately with the same error so I can help investigate, debug, and come up with a fix.)

**Comment by tianon** [comment]
Fix up at https://github.com/docker-library/redmine/pull/142. :+1:

**Comment by Silex** [comment]
@tianon: many thanks :pray:

**Comment by f466162** [comment]
My instance is back up after pulling the current image - thanks a lot! :+1:

**Comment by citiscaner** [comment]
Many thanks!

**Comment by hrmon** [comment]
Hi, I am still facing this problem with the exact same message. I don't know if I messed up somewhere.
Here is the docker-compose.yml:
```
version: "3"

services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      - PGDATA=/data/db
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=redmine
    volumes:
      - /data/db:/data/db

  redmine:
    image: redmine:3.4-passenger
    restart: always
    volumes:
      - /data/files:/usr/src/redmine/files
      - /data/plugins:/usr/src/redmine/plugins
      - /data/themes:/user/src/redmine/public/themes
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_PASSWORD=xxx
    depends_on:
      - postgres
```

And I have one plugin in `/data/plugins` with these permissions:
```
drwxr-xr-x 7 root root 4096 Dec 24 21:33 my_plugin
```

Can anyone help?
