### ISSUE TITLE
Redmine container fails to start 

### ISSUE THREAD

**Issue by vkrepkiy** [docker-library/redmine#138]
Hi! I'm using redmine:latest (tried also 3.4.6) with postgres:10.6. Everything worked fine till latest fresh build. If I omit using postgres (using sqlite3), i still receive the same redmine error:

**redmine container logs**
```
`/home/redmine` is not a directory.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
```

**postgres container logs**
```
ERROR:  relation "settings" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                             pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                        FROM pg_attribute a LEFT JOIN pg_attrdef d
                          ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                       WHERE a.attrelid = '"settings"'::regclass
                         AND a.attnum > 0 AND NOT a.attisdropped
                       ORDER BY a.attnum
```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by vkrepkiy** [comment]
@wglambert It really seems to be a duplicate of #137.  Can be reproduced with a docker-compose.yml with a **volumes** param (without it everything is ok):

**docker-compose.yml**
```
version: "3"
services:
  db:
    image: postgres:10.6-alpine
    restart: always
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=password
  redmine:
    image: redmine:3.4.6
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.data/redmine:/usr/src/redmine/files
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=password
```

**Comment by wglambert** [comment]
This is indeed the same issue as https://github.com/docker-library/redmine/issues/137#issuecomment-437820284, using an unpopulated Postgres volume will start without issue, using that now populated volume then gives permission errors about the home directory, and an additional `/ is not writable` error is encountered when using `--user` and (re)starting the container with a populated volume at `/var/lib/postgresql/data`. 

When reinitializing the container using its newly populated volume (this container is using your specific compose file)
```console
$ docker logs redmine
. . .
`/home/redmine` is not a directory.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
The Gemfile's dependencies are satisfied
[2018-11-14 21:25:01] INFO  WEBrick 1.3.1
[2018-11-14 21:25:01] INFO  ruby 2.4.5 (2018-10-18) [x86_64-linux]
[2018-11-14 21:25:01] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
```

With `--user: 1000:1001` (matching host user) a new `/ is not writable` is encountered
```console
$ docker logs redmine
. . .
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
. . .
```

The `/home/redmine is not a directory.` error isn't encountered when mounting `/home/redmine` with sufficient permissions, and also while not using the `--user` else the `/ is not writable` error is still encountered

So for instance this `docker-compose.yml` will work correctly through restarts with `/home/redmine` volumized and its host directory set with `777` permissions
```yml
version: "3"
services:
  db:
    image: postgres:10.6-alpine
    restart: always
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=password
  redmine:
    image: redmine:3.4.6
    restart: always
    volumes:
      - ./.data/redmine:/usr/src/redmine/files
      - ./redmine_home:/home/redmine
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=password
```

But if you're running as an arbitrary UID/GID it will error on re-using the now populated `/var/lib/postgresql/data`
