### ISSUE TITLE
Extract redmine user data

### ISSUE THREAD

**Issue by ManicPumpkin** [docker-library/redmine#153]
Hello,

I use Redmine since around two months now and I'm happy with it, but now, as I want to update my Redmine (which is in the docker-container) I found an issue. If I update the container, then my current docker container gets destroyed and all the data within. If I gonna set the "volumes" tag within the docker-compose.yml, then my data is also "gone", because the current data, which is safed in my current volume, is not transferred to this new directory on my host system. 

Is there a possibility to extract my current data, without losing it and use it as an external volume?

My current docker-compose.yml looks like that:
```
version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    volumes:
      - /home/rubnerda/Work/Docker/Redmine/data:/usr/src/redmine/files
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: 123456

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
```

Thank you very much!

**Comment by yosifkit** [comment]
Assuming that your initial deploy was with a compose file like so (ie sans any volumes):
```yaml
version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: 123456

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres

```

_Notes_: It is probably best to do most of this while the containers are stopped but not removed, so that the files won't be changed while you are trying to copy them. Be sure to do something similar to the postgres DB files too (maybe use `pg_dump`?). They will also be in an anonymous volume if you didn't define one.

### Option 1:

You could try using `docker cp`: https://docs.docker.com/engine/reference/commandline/cp/ on the container.

### Option 2

Do something like `docker run --rm --volumes-from=my_redmine_1 alpine tar c -f - /usr/src/redmine/files | tar -xf - /home/rubnerda/Work/Docker/Redmine/data` (untested).

### Option 3

Reach behind Docker's back and take the files directly. `docker container inspect my_redmine_1` and look at the `Source` path in `Mounts`

```console
$ docker container inspect my-container
....
        "Mounts": [
            {
                "Type": "volume",
                "Name": "0b0ee29c24cd5fa4af04ee1418d0c49d71198f72d490df369e0cf1d47eeedb08",
                "Source": "/mnt/nvme1/docker/volumes/0b0ee29c24cd5fa4af04ee1418d0c49d71198f72d490df369e0cf1d47eeedb08/_data",
                "Destination": "/var/lib/postgresql/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
....
$ # output abbreviated
```
