### ISSUE TITLE
Use envs in database.yml

### ISSUE THREAD

**Issue by clairton** [docker-library/redmine#168]
I like put in database.yml:

```yml

production:
  adapter: <%= ENV["REDMINE_DB_ADAPTER"] %>
  database: <%= ENV["REDMINE_DB_NAME"] %>
  host: <%= ENV["REDMINE_DB_HOST"] %>
  username: <%= ENV["REDMINE_DB_USER"] %>
  password: <%= ENV["REDMINE_DB_PASSWORD"] %>
  encoding: utf8

```

And throw `cp: can't stat 'Gemfile.lock.<%= ENV["REDMINE_DB_ADAPTER"] %>': No such file or directory`, this is solved by change de docker-entrypoint.sh script with:

```bash

adapter="$(ruby -e "
  require 'yaml'
  require 'erb'
  conf = YAML.load(ERB.new(File.read('./config/database.yml')).result)
  puts conf['$RAILS_ENV']['adapter']
")"

```

Instead of:

```bash

adapter="$(ruby -e "
  require 'yaml'
  require 'erb'
  conf = YAML.load_file('./config/database.yml')
  puts conf['$RAILS_ENV']['adapter']
")"

```
