### ISSUE TITLE
Critical error in README on docker hub

### ISSUE THREAD

**Issue by Carsak** [docker-library/redmine#178]
At readme on https://hub.docker.com/_/redmine says

```
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```

but in this case redmine server can start first before DB and user can get this error^
`Mysql2::Error::ConnectionError: Can't connect to MySQL server on 'db' (115)`

it need depend_on keyword 
https://docs.docker.com/compose/compose-file/#depends_on

like this:

```
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    hostname: redmine.local
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```
