### ISSUE TITLE
Fatal error on insert Cyrillic symbols

### ISSUE THREAD

**Issue by Carsak** [docker-library/redmine#179]
When I create new Issue with Cyrillic characters in string, for example 

> Интеграция с Gitlab
 

I got this error

```
redmine_1  | I, [2019-11-09T13:41:21.638651 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | I, [2019-11-09T13:41:21.662663 #1]  INFO -- : Completed 500 Internal Server Error in 70ms (ActiveRecord: 46.8ms)
redmine_1  | F, [2019-11-09T13:41:20.958816 #1] FATAL -- :
redmine_1  | F, [2019-11-09T13:41:20.958837 #1] FATAL -- : ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xD0\x98\xD0\xBD\xD1\x82...' for column 'subject' at row 1: INSERT INTO `issues` (`tracker_id`, `project_id`, `subject`, `description`, `status_id`, `priority_id`, `author_id`, `created_on`, `updated_on`, `start_date`, `lock_version`) VALUES (1, 1, 'Интеграция с Gitlab', '', 1, 1, 1, '2019-11-09 13:41:20', '2019-11-09 13:41:20', '2019-11-09', 0)):
redmine_1  | F, [2019-11-09T13:41:20.958849 #1] FATAL -- :
redmine_1  | F, [2019-11-09T13:41:20.958859 #1] FATAL -- : app/models/issue.rb:209:in `create_or_update'
```

My docker-compose file
```

version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    hostname: redmine.local
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      # REDMINE_NO_DB_MIGRATE: "true"
    volumes:
      - ./docker/redmine-data:/usr/src/redmine/files
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
```

**Comment by wglambert** [comment]
You'll want to add the locales to your redmine and database images

```dockerfile
FROM redmine
  
RUN apt update && apt install -y locales \
 && rm -rf /var/lib/apt/lists/* \
 && localedef -i kk_KZ -c -f UTF-8 -A /usr/share/locale/locale.alias kk_KZ.UTF-8
ENV LANG kk_KZ.utf8
ENV LC_ALL kk_KZ.utf8
```

You'll want to change the collation as well, I just changed the character-set to be safe
```yml
version: '3.1'
  
services:

  redmine:
    image: redmine:kz
    restart: always
    hostname: redmine.local
    ports:
      - 9090:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db

  db:
    image: mysql:57-kz
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
```

<details>
<summary> docker build </summary>

```console
$ docker build . -t redmine:kz
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM redmine
 ---> 8023a425328b
Step 2/4 : RUN apt update && apt install -y locales  && rm -rf /var/lib/apt/lists/*  && localedef -i kk_KZ -c -f UTF-8 -A /usr/share/locale/locale.alias kk_KZ.UTF-8
 ---> Running in a80690f05fe1
                                                                                                                                                                            
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.                                                                                             
                                                                                                                                                                            
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]                                                                                     
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [122 kB]                                                                                                     
Get:3 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [49.3 kB]                                                                                            
Get:4 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [113 kB]                                                                            
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7899 kB]                                                                                          
Get:6 http://cdn-fastly.deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]                                                                                   
Fetched 8227 kB in 2s (3838 kB/s)                                                                                                                                           
Reading package lists...                                                                                                                                                    
Building dependency tree...                                                                                                                                                 
Reading state information...                                                                                                                                                
All packages are up to date.                                                                                                                                                
                                                                                                                                                                            
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.                                                                                             
                                                                                                                                                                            
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libc-l10n
The following NEW packages will be installed:
  libc-l10n locales
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 4907 kB of archives.
After this operation, 20.8 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libc-l10n all 2.28-10 [847 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 locales all 2.28-10 [4060 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 4907 kB in 1s (4789 kB/s)
Selecting previously unselected package libc-l10n.
(Reading database ... 15355 files and directories currently installed.)
Preparing to unpack .../libc-l10n_2.28-10_all.deb ...
Unpacking libc-l10n (2.28-10) ...
Selecting previously unselected package locales.
Preparing to unpack .../locales_2.28-10_all.deb ...
Unpacking locales (2.28-10) ...
Setting up libc-l10n (2.28-10) ...
Setting up locales (2.28-10) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Generating locales (this might take a while)...
Generation complete.
Removing intermediate container a80690f05fe1
 ---> 57dc6a566c0e
Step 3/4 : ENV LANG kk_KZ.utf8
 ---> Running in 3589e837dc1f
Removing intermediate container 3589e837dc1f
 ---> fec1f15cf8f1
Step 4/4 : ENV LC_ALL kk_KZ.utf8
 ---> Running in 46c6d2cabb74
Removing intermediate container 46c6d2cabb74
 ---> 73d636b2d52d
Successfully built 73d636b2d52d
Successfully tagged redmine:kz


$ docker run --rm redmine:kz locale
LANG=kk_KZ.utf8
LANGUAGE=
LC_CTYPE="kk_KZ.utf8"
LC_NUMERIC="kk_KZ.utf8"
LC_TIME="kk_KZ.utf8"
LC_COLLATE="kk_KZ.utf8"
LC_MONETARY="kk_KZ.utf8"
LC_MESSAGES="kk_KZ.utf8"
LC_PAPER="kk_KZ.utf8"
LC_NAME="kk_KZ.utf8"
LC_ADDRESS="kk_KZ.utf8"
LC_TELEPHONE="kk_KZ.utf8"
LC_MEASUREMENT="kk_KZ.utf8"
LC_IDENTIFICATION="kk_KZ.utf8"
LC_ALL=kk_KZ.utf8
```

</details>

![image](https://user-images.githubusercontent.com/26428991/68610586-f284f400-046c-11ea-93c0-ba50affc8625.png)

```console
$ docker exec -it redmeme_db_1 mysql -uroot -pexample -Dredmine
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.27 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select * from projects;
+----+--------------------+------------------+----------+-----------+-----------+---------------------+---------------------+------------+--------+------+------+-----------------+--------------------+------------------------+
| id | name               | description      | homepage | is_public | parent_id | created_on          | updated_on          | identifier | status | lft  | rgt  | inherit_members | default_version_id | default_assigned_to_id |
+----+--------------------+------------------+----------+-----------+-----------+---------------------+---------------------+------------+--------+------+------+-----------------+--------------------+------------------------+
|  1 | испытание          | описание         |          |         1 |      NULL | 2019-11-11 18:19:40 | 2019-11-11 18:19:40 | identifier |      1 |    1 |    2 |               0 |               NULL |                   NULL |
+----+--------------------+------------------+----------+-----------+-----------+---------------------+---------------------+------------+--------+------+------+-----------------+--------------------+------------------------+
1 row in set (0,00 sec)
```

**Comment by Carsak** [comment]
I got this error 
```
Pulling db (mysql:57-kz)...
ERROR: manifest for mysql:57-kz not found
```

Maybe need another image?

**Comment by Carsak** [comment]
With this docker-compose file
```

version: '3.1'

services:

  redmine:
    image: redmine:kz 
    restart: always
    hostname: redmine.local
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_NO_DB_MIGRATE: "true"
      # REDMINE_DB_ENCODING: utf8
      # LANG: C.UTF-8
      # LC_ALL: C.UTF-8
    volumes:
      - ./docker/redmine-data:/usr/src/redmine/files
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
      # LANG: C.UTF-8
      # LC_ALL: C.UTF-8
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    command:
    - "--character-set-server=utf8mb4"
    - "--collation-server=utf8mb4_unicode_ci"
```


I get this error

```

Completed 500 Internal Server Error in 124ms (ActiveRecord: 107.3ms)
redmine_1  | F, [2019-11-12T16:58:18.639302 #1] FATAL -- :
redmine_1  | F, [2019-11-12T16:58:18.639327 #1] FATAL -- : ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xD0\x98\xD0\xBD\xD1\x82...' for column 'subject' at row 1: INSERT INTO `issues` (`tracker_id`, `project_id`, `subject`, `description`, `status_id`, `priority_id`, `author_id`, `created_on`, `updated_on`, `start_date`, `lock_version`) VALUES (1, 1, 'Интеграция с Gitlab', '', 1, 1, 1, '2019-11-12 16:58:18', '2019-11-12 16:58:18', '2019-11-12', 0)):
redmine_1  | F, [2019-11-12T16:58:18.639339 #1] FATAL -- :
redmine_1  | F, [2019-11-12T16:58:18.639349 #1] FATAL -- : app/models/issue.rb:209:in `create_or_update'
redmine_1  | app/controllers/issues_controller.rb:130:in `create'
redmine_1  | lib/redmine/sudo_mode.rb:63:in `sudo_mode'
redmine_1  | I, [2019-11-12T16:58:19.059380 #1]  INFO -- : Started POST "/projects/map/issues" for 172.21.0.1 at 2019-11-12 16:58:19 +0000
redmine_1  | I, [2019-11-12T16:58:19.061038 #1]  INFO -- : Processing by IssuesController#create as HTML
redmine_1  | I, [2019-11-12T16:58:19.061192 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"V9z7zvHlseQ1oX30wv98MJEC6S/0SceInYWtxuvzlsVUpGr8qAVf2R8MFPWwBgkE4AKiGVsinm2Jg+Vp5RrkYA==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "tracker_id"=>"1", "subject"=>"Интеграция с Gitlab", "description"=>"", "status_id"=>"1", "priority_id"=>"1", "assigned_to_id"=>"", "parent_issue_id"=>"", "start_date"=>"2019-11-12", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0", "watcher_user_ids"=>[""]}, "was_default_status"=>"1", "commit"=>"Создать", "project_id"=>"map"}
```

My locole in redmine:kz image
![image](https://user-images.githubusercontent.com/9497934/68692860-6a077000-05a0-11ea-8f93-174078cd9e18.png)

**Comment by Carsak** [comment]
I do all thing
1. create 2 images with kz UTF-8
2. launch with new docker-compose
```
version: '3.1'
  
services:

  redmine:
    image: redmine:kz
    restart: always
    hostname: redmine.local
    ports:
      - 9090:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db

  db:
    image: mysql:57-kz
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
```
But sill get error;
Than I realized that all tables is with latin1
```
docker exec -ti redmineexample_db_1 mysql -uroot -pexample -Dredmine
use redmine;
show create table issues;
```
**`ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1`**

Than I Drop all tables
Restart migrate
Profit
`ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |`

Error disappear, I can insert multibyte strings

![image](https://user-images.githubusercontent.com/9497934/68697184-83141f00-05a8-11ea-9cb4-89ae1ee059b6.png)


I think all problems was in incorrect table encoding

@wglambert 
thank you for your help!
