### ISSUE TITLE
entrypoint.sh fails to bind to database using docker-compose version 2

### ISSUE THREAD

**Issue by julienfastre** [docker-library/redmine#18]
Hi,

(at first: thank for your work)

We use the redmine image with docker compose. The `entrypoint.sh` fails to use the postgres database, linked to the container, because docker-compose files written with version 2 does not create environment variables which allow the entrypoint.sh script to "detect" that a database is attached : 

From [the documentation](https://docs.docker.com/compose/link-env-deprecated/) : 

> **Note:** Environment variables are no longer the recommended method for connecting to linked services. Instead, you should use the link name (by default, the name of the linked service) as the hostname to connect to. See the docker-compose.yml documentation for details.
>
> Environment variables will only be populated if you’re using the legacy version 1 Compose file format.

When I ran my container, I had this environement : 

```
PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=27d8f3cd44c1
RUBY_MAJOR=2.2
RUBY_VERSION=2.2.4
RUBY_DOWNLOAD_SHA256=b6eff568b48e0fda76e5a36333175df049b204e91217aa32a65153cc0cdcb761
RUBYGEMS_VERSION=2.5.1
GEM_HOME=/usr/local/bundle
BUNDLER_VERSION=1.11.2
BUNDLE_APP_CONFIG=/usr/local/bundle
RAILS_ENV=production
REDMINE_VERSION=3.2.0
REDMINE_DOWNLOAD_MD5=b1050c3a0e6effd5a704ef5003d9df06
PASSENGER_VERSION=5.0.23
HOME=/root
```

I had to add manually the environment values in the `docker-compose.yml` file : 

```
version: '2'

services:
  db: 
    image: postgres:9.5
    environment:
      - PGDATA=/pgsql
    volumes:
      - redmine_cl_postgres:/pgsql
  phusion:
    # our image, which extends the redmine:phusion base image
    image: champslibres/redmine
    environment:
        # I had to add environment values here :
      - POSTGRES_PORT_5432_TCP=tcp://postgres:5432
      - POSTGRES_ENV_POSTGRES_USER=xxxx
      - POSTGRES_ENV_POSTGRES_PASSWORD=xxxx
      - POSTGRES_ENV_POSTGRES_DB=xxxx
    volumes:
      - redmine_cl_attachements:/usr/src/redmine/files
      - /root/redmine_cl_phusion.custom/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
    links:
      - db:postgres
    ports:
      - "127.0.0.1:3010:3000"

volumes:
  redmine_postgres:
    external: true
  redmine_attachements:
    external: true
```

Is there another way to solve this problem ?

Regards,
