### ISSUE TITLE
Always restart redmine 4.0.X

### ISSUE THREAD

**Issue by terentev-mn** [docker-library/redmine#180]
My configs:
Dockerfile
```
FROM redmine:4.0.5-passenger 
RUN apt-get update
```
docker-compose.yml
```
version: "3.6"

volumes:
  redmine-plugins:
  redmine-themes:
  redmine-files:
  redmine-models:

services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - /srv/storage/redmine/mysqlconf:/etc/mysql/conf.d
      - /srv/storage/redmine/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ssssss"
      MYSQL_DATABASE: "redmine"
      TZ: "Europe/Minsk"
    restart: always

  redmine:
    build:
      context: .
    image: redmine:custom
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-themes:/usr/src/redmine/public/themes
      - redmine-files:/usr/src/redmine/files
      - redmine-models:/usr/src/redmine/app/models
      - /srv/storage/redmine/configuration.yml:/usr/src/redmine/config/configuration.yml
    environment:
      REDMINE_DB_MYSQL: "mysql"
      REDMINE_DB_USERNAME: "redmine"
      REDMINE_DB_PASSWORD: "xxxxx"
      REDMINE_PLUGINS_MIGRATE: "True"
      REDMINE_SECRET_KEY_BASE: "..."
      TZ: "Europe/Minsk"
    restart: always
```
I try start container
``docker-compose up -d --force-recreate --build``

and got error:
```
redmine_1  | /usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
redmine_1  | Tasks: TOP => db:migrate => db:load_config => environment
redmine_1  | (See full trace by running task with --trace)
redmine_1  | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
redmine_1  | The Gemfile's dependencies are satisfied
redmine_1  | rake aborted!
redmine_1  | NoMethodError: undefined method `attr_protected' for #<Class:0x0000557e6dd54968>
redmine_1  | Did you mean?  attr_reader
redmine_1  | /usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
redmine_1  | /usr/src/redmine/app/models/custom_field.rb:38:in `<class:CustomField>'
redmine_1  | /usr/src/redmine/app/models/custom_field.rb:18:in `<top (required)>
```

Please help! What is wrong?
