### ISSUE TITLE
Useage of real URL and existing SSL certificate in compose

### ISSUE THREAD

**Issue by bertalanimre** [docker-library/redmine#191]
I've locally set up the container, simple, easy to attach external folders and ports. But deploying it to our production server is messy.

Production environment:
* CentOS 7
* Installed NginX using 80 and 443 ports
* docker --version -> Docker version 19.03.4, build 9013bf583a
* docker-compose --version -> docker-compose version 1.23.2, build 1110ad01

What I want to achieve is accept every incoming connection to my NginX via 443 and forward it with the URL unchanged to the docker container.

I've been using the following `docker-compose.yml`

```
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
#    ports:
#      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: <EXTERNAL-DB-IPADDRESS>
      REDMINE_DB_PORT: 3306
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmineadmin
      REDMINE_DB_PASSWORD: "topsecret"
    volumes:
      - /home/bi/sites/redmine/docker-redmine/redmine4.mycompany.com/files:/usr/src/redmine/files
      - /etc/nginx/ssl:/etc/ssl/redmine:ro
    networks:
      redmine_net:
        ipv4_address: 172.28.1.1

networks:
    redmine_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
```

And here is my NginX config file

```
server	{
	listen 3000;

	server_name	redmine4.mycompany.com;

	large_client_header_buffers 4 32k;

	location / {
		proxy_pass http://172.28.1.1:3000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

```

Or anyone knows how to tell the container to receive incoming traffic via the URL? Also, how to tell the container to use the SSL access only? I know about
```
passenger start --ssl \
        --ssl-certificate /etc/ssl/redmine/server.pem \
        --ssl-certificate-key /etc/ssl/redmine/server.key \
        --ssl-port 3443
```
when I would like to execute `docker run` but I have no clue where to include this in the `docker-compose.yml` file.
