### ISSUE TITLE
Ineffective UTF-8 configuration

### ISSUE THREAD

**Issue by pini-gh** [docker-library/redmine#198]
Hi,
I've set up a new docker-redmine instance to take over an existing project currently on hosteredmine.com. Here is how I proceeded:
1. Export the project from export.hostedredmine.com
1. `docker-compose up -d` with this docker-compose.yml file:
```
version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      - REDMINE_DB_MYSQL=mysql
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=<redacted>
      - REDMINE_DB_ENCODING=utf8mb4
      - REDMINE_SECRET_KEY_BASE=<redacted>
    networks:
      internal:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<redacted>
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=<redacted>
    volumes:
    - mysql-vol:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      internal:

volumes:
   mysql-vol:

networks:
   internal:
     driver: bridge
```
1. Stop the redmine container: `docker-compose stop redmine`
1. Import the previously exported hostedredmine database: `docker exec -i redmine_mysql_1 mysql -u redmine --password=<redacted> redmine <../hostedredmine.com/database_26748.sql`
1. Restart the redmine container: `docker-compose up -d`

I've checked poking into the mysql database that the encoding looks OK:
```
mysql> select * from issue_checklists;
+--------+---------+---------------------------------------------------------------------------------------------+----------+----------+
| id     | is_done | subject                                                                                     | position | issue_id |
+--------+---------+---------------------------------------------------------------------------------------------+----------+----------+
| 267749 |    NULL | Create and implement                                                                        |    40012 |   537969 |
| 267755 |    NULL | Create rest services                                                                        |    40013 |   537970 |
| 268207 |       1 | галерија за листање на промоции                                  |    40106 |   538276 |
| 268246 |       1 | tree                                                                                        |    40117 |   534783 |
| 275619 |    NULL | Общий свод ЗП в 2.5 и 3.0 сильно расходится                    |    41323 |   531790 |
| 275620 |    NULL | Отпуска по уходу за ребенком не вошли в общий свод |    41324 |   531790 |
| 284040 |       1 | Supervisores                                                                                |    42836 |   562060 |
| 284069 |       1 | neue Liga "Euro 2016" erzeugen                                                              |    42848 |   491460 |
| 293648 |    NULL | 文字中是否有等等，省略用语，内容是否清晰不含糊？                    |    45387 |   597190 |
| 293651 |    NULL | 是否进行外部接口分析？                                                           |    45388 |   597190 |
| 293652 |    NULL | 是否进行内部接口分析？                                                           |    45389 |   597190 |
| 300287 |       1 | liiga.png                                                                                   |    46567 |   599963 |
| 304180 |    NULL | moze jakieś bardziej logiczne wpinanie nagłówków dla głównych modułów               |    47452 |   647536 |
| 307924 |    NULL | #EXTINF:-1,OTV - ARAB                                                                       |    48246 |   661887 |
+--------+---------+---------------------------------------------------------------------------------------------+----------+----------+
14 rows in set (0.02 sec)
```
But when using the redmine web interface UTF-8 characters are not correctly rendered (such as `DÃ©filÃ©` for `Défilé`) and when creating a new issue with accentuated characters they appear iso8859 encoded into the database:
```
mysql> select subject from issues where subject like 'Test%';
+------------------------+
| subject                |
+------------------------+
| Test blabla &�"'(-�_�� |
+------------------------+
1 row in set (0.00 sec)
```
Any clue appreciated.
