### ISSUE TITLE
Email configuration

### ISSUE THREAD

**Issue by belak** [docker-library/redmine#20]
There is currently no easy way to provide an email configuration. You would need to create a config file and bind it manually.

If that's the recommended solution, I can close this, but it seems like there has to be a better way, especially since this goes to all the trouble of generating a `config/database.yml`.

**Comment by theblackhole** [comment]
+1 for an easy smtp config. I've seen it on [bitnami-docker-redmine](https://github.com/bitnami/bitnami-docker-redmine#smtp-configuration) but it don't know if it's hard or not to implement this option.

**Comment by bigkun** [comment]
how to configure the 'smtp ' settings?

**Comment by stefcl** [comment]
@bigkun 
Then, create a configuration.yml file on the host system with the correct info (check
http://www.redmine.org/projects/redmine/wiki/FrRedmineConfigurationEmail for the exact syntax) and mount it as a volume in the container, the relevant lines in my docker compose file looks like this :

```
    volumes:
      - ${BASE_DIR}/data/files:/usr/src/redmine/files
      - ${BASE_DIR}/data/configuration.yml:/usr/src/redmine/config/configuration.yml
```

`BASE_DIR` is an environment file on my system mapping to my container root folder.

Not that complex but I agree with the commenters above, making use of environment variables would be a bit less flexible but much nicer for the vast majority of cases.

**Comment by plastikschnitzer** [comment]
@stefcl how does your configuration.yml file look like? Just email config or all the other configs as well? I tried everything, checked for correct yml setup with empty spaces instead of tabs, tried different email servers and configs but redmine does not send emails and saving issue updates takes 15 seconds to one minute, I guess its due to timeouts.
Do I have to restart redmine after every change of the configuration.yml file or is it grabbed every time redmine sends an email and I can change it without redmine restarts?

**Comment by stefcl** [comment]
@plastikschnitzer your `configuration.yml` file should only contain the sections that you want to override, do not bother copying the complete example file.

This is my whole file:

```
default:
  # Outgoing emails configuration (see examples above)
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      tls: false
      address: mail.myemaildomain.com
      port: 587
      domain: myemaildomain.com
      authentication: :login
      user_name: "redmine@myemaildomain.com"
      password: "my-secret-password"
      openssl_verify_mode: 'none'

```
(Most of the information comes from my email hoster, I just copied from one of their smtp client configuration guide, I just changed the domain name and password for obvious reasons).

Full reference here :
http://www.redmine.org/projects/redmine/wiki/FrRedmineConfigurationEmail

If you are using a docker mount, the config file changes on the host will be immediately visible in the container but I can not tell for sure whether config file is re-parsed every time or not, just restart your container to be absolutely sure. 

If nothing works, open a bash terminal to your running container with the following command (mine is named `redmine`, do a `docker ps` if you are not sure about the name):

     docker exec -ti redmine /bin/bash

then check that the config file is mounted and present as expected

     cat /usr/src/redmine/config/configuration.yml

last but not least, check the log file

     cat /usr/src/redmine/log/production.log

for any useful information. 
Hope this helps

**Comment by plastikschnitzer** [comment]
Thank you very much for your help!

I also mount my custom theme from external and here every change is picked up with a simple page reload. Same about the email config, I checked with the bash terminal in my running container.

The logfile has the following statement about the email delivery, I tried two different mailservers, same result:

```
Current user: admin (id=1)
Rendered mailer/_issue.text.erb (5.4ms)
Rendered mailer/issue_edit.text.erb within layouts/mailer (11.0ms)
Rendered mailer/_issue.html.erb (0.8ms)
Rendered mailer/issue_edit.html.erb within layouts/mailer (6.0ms)
Email delivery error: end of file reached
```

**Comment by stefcl** [comment]
@plastikschnitzer 
As a possible hint, that EOF issue in the log reminds me TLS / handshake issues. Have you tried playing with `tls` and `enable_starttls_auto` true / false ?

Also, if you are using commons smtp ports such as 25, be aware that some hosters restrict them without much advertisement to prevent hackers from turning them into spamming bots. It recently happened to me with Scaleway, and I had to tweak some settings in my account dashboard to be able to use the port normally.

**Comment by plastikschnitzer** [comment]
Yes, I tried with these settings and ports. The mailboxes are working fine with local mailclients and other applications, but not from redmine inside of docker. 

Its my own root server so I tried with the local smtp server:

```
default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 25
```
But the error still stays the same. I can send emails from the server CLI with:
`echo "This is the body of the email" | mail -s "subject line" myemail@domain.tld`

Is it possible that redmine can not reach outside the docker container where its running in? 

This is the redmine docker command I used:

`docker run -d -p 3000:3000 -v /some/local/dir/config/configuration.yml:/usr/src/redmine/config/configuration.yml --link redmine-mysql:mysql redmine`

I then mapped a domain with reverse proxy to redmine and everything is working fine aside the mail notifications from redmine …

**Comment by plastikschnitzer** [comment]
OK, solved it! I turned out I really had to kill the container and run it again, mail config was working from that moment on.
Thank you very much for your help!

**Comment by vijaygill** [comment]
> Yes, I tried with these settings and ports. The mailboxes are working fine with local mailclients and other applications, but not from redmine inside of docker.
> 
> Its my own root server so I tried with the local smtp server:
> 
> ```
> default:
>   email_delivery:
>     delivery_method: :smtp
>     smtp_settings:
>       address: localhost
>       port: 25
> ```
> But the error still stays the same. I can send emails from the server CLI with:
> `echo "This is the body of the email" | mail -s "subject line" myemail@domain.tld`
> 
> Is it possible that redmine can not reach outside the docker container where its running in?
> 
> This is the redmine docker command I used:
> 
> `docker run -d -p 3000:3000 -v /some/local/dir/config/configuration.yml:/usr/src/redmine/config/configuration.yml --link redmine-mysql:mysql redmine`
> 
> I then mapped a domain with reverse proxy to redmine and everything is working fine aside the mail notifications from redmine …

@plastikschnitzer I took hint from your post and got email working but I had to change the smtp server from localhost to the IP address of the host where SMTP server (sendmail on a raspberry pi) is running in my setup. Also I had to enable relaying in the sendmail access file to allow relaying mail from container to outside world. Now mails are flowing freely from my docker container on a raspberry pi (yes redmine is also on a raspberry pi)!

**Comment by stefcl** [comment]
> > Its my own root server so I tried with the local smtp server:
> > ```
> > default:
> >   email_delivery:
> >     delivery_method: :smtp
> >     smtp_settings:
> >       address: localhost
> >       port: 25
> > ```

> > Is it possible that redmine can not reach outside the docker container where its running in?

In the context of docker, localhost:25 will look for a service running inside the container, not on the host network.

You can confirm that by replacing "localhost" with your server public IP, provided that your smtp service is accessible from the outside world.

**Comment by michaelmcandrew** [comment]
Note that in addition to https://www.redmine.org/projects/redmine/wiki/EmailConfiguration, you might find https://github.com/redmine/redmine/blob/master/config/configuration.yml.example useful as a canonical reference for what to put in your configuration.yml.

**Comment by Kounex** [comment]
> delivery_method: :smtp smtp_settings: tls: false address: mail.myemaildomain.com port: 587 domain: myemaildomain.com authentication: :login user_name: "redmine@myemaildomain.com" password: "my-secret-password" openssl_verify_mode: 'none'

It's been a while but maybe you could help me out since you even considered this case. I'm using redmine as a package installed on a DSM which in the end starts a docker container. My problem is, that after every restart of the container - the configuration.yml gets set back to "default" which is missing the config for mailing. I just can't see from where it gets overriden every time since modifying other files as production.rb etc. persist. If you have any clue I would really appreciate the help!

**Comment by stefcl** [comment]
> 
> It's been a while but maybe you could help me out since you even considered this case. I'm using redmine as a package installed on a DSM which in the end starts a docker container. My problem is, that after every restart of the container - the configuration.yml gets set back to "default" which is missing the config for mailing. I just can't see from where it gets overriden every time since modifying other files as production.rb etc. persist. If you have any clue I would really appreciate the help!

If your modified config file gets replaced by the original one every time, the most probable cause is that the file in question is **not** on a mounted volume.

Have a look at the docker command or compose file used by your system to create the container and make sure the configuration file is present as a volume. Then, if you are convinced that your mount is correct and that some process in the image is overwriting your files, try mounting the volume in read-only mode and check what happens.

**Comment by Kounex** [comment]
Thanks for helping me out here! I was able to solve this problem - changes I generally made did persist so it was not a problem with missing a persistent volume. Missing key information I haven’t mentioned: I’m using the configurated version of the redmine docker image from sameersbn. After reading the manual, which I clearly should have done before, the mail configuration is being set by environment variables at startup. So without setting those variables it gets set to defauIt at startup. I had to set the appropriate variables for the container in docker and now everything works like a charm.

Thanks a lot!

**Comment by Tb0b** [comment]
Hi, I've the same issue using K8s and kubectl to deploy redmine.
Even if I try to declare a volumemount in my yaml file redmine container can't use it, i still have
"rake aborted! 
LoadError: cannot load such file -- /usr/src/redmine/config/application"

and naturally if I edit configuration.yml in my container using shell/vim , when I restart it the file is crushed.

anybody has a solution with k8s ?

**Comment by ismailbaskin** [comment]
It's hard to mount a single configuration.yml file to the Redmine container. Also supporting every parameter with ENV variables is not sustainable. [Nginx](https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119) had the same problem too. 

They solved this problem with env substitution. We can mount template file(s) to `/etc/redmine/templates/*.yml.template` and `entrypoint.sh` can merge ENV variables with this template and write into the exact place of yml. Can we use the same approach?

**Comment by tianon** [comment]
AFAIK, Redmine already runs `configuration.yml` through ERB, so you should be able to do even more powerful substitutions by default than `envsubst` can provide. :smile:

**Comment by ismailbaskin** [comment]
I'm unfamiliar with Redmine's internal but it's still hard to mount `config/environments/production.rb` file with Kubernetes configMap. I've solved this problem by executing a bash cp command on postStart.

**Comment by x3nb63** [comment]
> I'm unfamiliar with Redmine's internal but it's still hard to mount `config/environments/production.rb` file with Kubernetes configMap. I've solved this problem by executing a bash cp command on postStart.

THAT put me on the right track to get a `configuration.yml` injected from ConfigMap, thanks!

Problem is the [_fix_permissions() function in docker-entrypoint.sh](https://github.com/docker-library/redmine/blob/master/4.1/docker-entrypoint.sh). It wants to chown/chmod on everything in the `config/` directory. This fails when `config/configuration.yml` is mounted from ConfigMap cause ConfigMaps are always read only ...

here is how it looks in my deployment:

```
container:
...
           volumeMounts:
            - name: redmine-config
              mountPath: /etc/redmine/configuration.yml
              subPath: configuration.yml
...
          lifecycle:
            postStart:
              exec:
                command: ['/bin/cp', '-v',
                          '/etc/redmine/configuration.yml',
                          '/usr/src/redmine/config/configuration.yml']
...
       volumes:
         - name: redmine-config
           configMap:
             name: projects
             items:
               - key: "configuration.yml"
                 path: "configuration.yml"
...
```

I'd suggest to somehow change the `_fix_permissions()` function to be less blunt (dont know how right now)

or change Dockerfile to provide a separate volume for configuration files, which the entrypoint copies to their right locations if present.

**Comment by tianon** [comment]
The simplest answer is going to be that the `chown` in that function is conditional and the `chmod` lines already include `|| :` (so errors there are non-fatal), so if you run your container as a non-root user it should "Just Work" (the entrypoint uses `redmine:redmine` after it finishes that `chown`/`chmod` combo, so perhaps that's the value you want?)

**Comment by x3nb63** [comment]
n

> (the entrypoint uses `redmine:redmine` after it finishes that `chown`/`chmod` combo, so perhaps that's the value you want?)

When the file is made by a ConfigMap the chown can not work, no matter which user/group is given. Its some memory-mapped read-only thing, always. Thats a Kubernetes specific issue, this script just trips over.

just read [Step 8 - File system permissions](https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-8-File-system-permissions): it does not explicitly mention `config/`. So it could just be removed if this function is to implement that step.

For `files/` and `log/` its correct to fail on chown (and also chmod should fail) cause while redmine is running it will produce lots of ruby exceptions all over the place if there is a permission issue anywhere in these ...

**Comment by emilyvdh-t** [comment]
@plastikschnitzer 
> OK, solved it! I turned out I really had to kill the container and run it again, mail config was working from that moment on. I had to mount new volumes and voila from that moment on, everything was working like expected with sending mails...
> Thank you very much for your help!

Please could you be explicit about 'I had to mount to volumes'? 
I am trying to do this using the docker-compose.yml file that I use to start the containers, but no luck so far. 
I want the email configuration file I have created on my host system to persist when I restart the container. 
My docker-compose.yml looks like this:

```
version: '3.1'

services:

  redmine:
    image: redmine
    container_name: trameto-redmine
    restart: always
    ports:
        - 8080:3000
    depends_on:
        - db
    volumes: 
        - db-data:/var/lib/mysql-files
    environment:
        REDMINE_DB_MYSQL: db
        REDMINE_DB_PASSWORD: xxxx

  db:
    image: mysql:5.7
    container_name: trameto-mysql
    restart: always
    environment:   
        MYSQL_DATABASE: redmine
        MYSQL_ROOT_PASSWORD: xxxx
    volumes:
     - "/home/tools/redmine/data/files:/usr/src/redmine/files"
     - "/home/tools/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml"

```
I don't understand the differences/mapping between 'docker run' commands and their equivalents in a *yml file, so any/all explanation  would be appreciated please.
