### ISSUE TITLE
Using SQLite fallback

### ISSUE THREAD

**Issue by mcondarelli** [docker-library/redmine#206]
Due to my meager needs I would like to use SQLite as db.
Starting the image with standard options:
```
docker run -it --rm \
           --name sqlite-redmine \
           --publish 3000:3000 \
           --volume /srv/docker/sqlite_redmine/files:/usr/src/redmine/files \
           redmine
```
works as expected, but database is wiped each time (unsurprisingly).
Adding a few options:
```
docker run -it --rm \
           --name sqlite-redmine \
           --publish 3000:3000 \
           --volume /srv/docker/sqlite_redmine/files:/usr/src/redmine/files \
           --volume /srv/docker/sqlite_redmine/sqlite:/usr/src/redmine/sqlite \
           --volume /srv/docker/sqlite_redmine/plugins:/usr/src/redmine/plugins \
           redmine
```
bombs because it seems the database is not created:
```
warning: missing REDMINE_DB_MYSQL, REDMINE_DB_POSTGRES, or REDMINE_DB_SQLSERVER environment variables

*** Using sqlite3 as fallback. ***

The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
The Gemfile's dependencies are satisfied
rake aborted!
SQLite3::CantOpenException: unable to open database file
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:89:in `open_v2'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:89:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:32:in `new'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:32:in `sqlite3_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_handling.rb:90:in `connection'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
How am I supposed to handle this?

**Comment by wglambert** [comment]
Your directories on the host need appropriate permissions for the user `999` in the container

So either making the user `999` the owner of the directories and setting permissions to `7xx`
Or setting the permissions to `777`

**Comment by wglambert** [comment]
You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by jperelli** [comment]
I've been 2 days trying to fix this the cleanest way. For future reference for myself and anyone interested:

I ended up doing the following

docker-compose.yml
```yaml
version: '3'
services:

  redmine:
    image: redmine:5.1-bookworm
    ports:
      - 3000:3000
    environment:
      # - REDMINE_DB_DATABASE=/sqlite/redmine.db
      - REDMINE_PLUGINS_MIGRATE=true
    volumes:
      - ./.volumes/files:/usr/src/redmine/files
      - ./.volumes/sqlite:/usr/src/redmine/sqlite
      - ./:/usr/src/redmine/plugins/periodictask
    depends_on:
      - redmine_fix_permissions

  redmine_fix_permissions:
    image: redmine:5.1-bookworm
    volumes:
      - ./.volumes/sqlite:/usr/src/redmine/sqlite
    command: chown 999:999 /usr/src/redmine/sqlite
```

and with
```
docker compose up
```

I get the .volumes/sqlite/redmine.db file outside the container and all working fine.
