### ISSUE TITLE
Docker composes Redmine 4.1.1 + Sidekiq

### ISSUE THREAD

**Issue by contentadore** [docker-library/redmine#222]
Hello. Thanks for your work with Redmine docker.

I researched different articles about it.
https://dev.to/raphael_jambalos/more-than-hello-world-in-docker-run-rails-sidekiq-web-apps-in-docker-1b37
https://nickjanetakis.com/blog/dockerize-a-rails-5-postgres-redis-sidekiq-action-cable-app-with-docker-compose
etc.

They use 2nd service similar main app and start command "bundle exec sidekiq ...".

```
  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.env'
```
I tried to make it with Redmine docker and that didn't find bundler or sidekiq.
Then I decided to rebuild Redmine Dockerfile and changed docker-entrypoint.sh
Added these strings at the end of the docker-entrypoint.sh:

```
gosu redmine gem install sidekiq

gosu redmine bundle install

gosu redmine /bin/bash -lc '/usr/local/bin/bundle exec sidekiq -e production' 

#exec "$@" # Disabled because it doesn't need to start "rails server" with sidekiq service
```

Then added env variable DATABASE_URL and SECRET_KEY_BASE to docker-compose.yml because that's also required by Sidekiq without config/database.yml

```
DATABASE_URL: "postgres://user:pass@database"
SECRET_KEY_BASE: "..."
```
Result:
```
redmine_1   | Please configure your config/database.yml first
redmine_1   | bundler: failed to load command: sidekiq (/usr/local/bundle/bin/si
dekiq)
redmine_1   | LoadError: Error loading the 'postgresql' Active Record adapter. M
issing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.
```
Then I tried to install gems 'pg' and 'activerecord-postgres-adapter' in docker-entrypoint.sh and Dockerfile but that also failed.
Not sure what else to try.

Current docker-compose.yml
```

version: '3.8'
services:
   postgres:
     image: postgres:13
     volumes:
       - ./postgresql-data:/var/lib/postgresql/data
     environment:
       POSTGRES_USER: "user"
       POSTGRES_PASSWORD: "pass"
       POSTGRES_DB: "database"
     restart: always
   redmine:
     build:
       context: .
     image: redmine:custom
     ports:
       - 80:3000
     volumes:
       - ./redmine-plugins:/usr/src/redmine/plugins
 environment:
       REDMINE_DB_POSTGRES: postgres
       REDMINE_DB_USERNAME: "user"
       REDMINE_DB_PASSWORD: "pass"
       REDMINE_DB_DATABASE: "database"
       REDMINE_SECRET_KEY_BASE: "..."
       SECRET_KEY_BASE: "..."
     restart: always
     depends_on:
       - redis
       - postgres
   sidekiq:
     build:
       context: .
     image: redmine:sidekiq
     #command: /bin/bash -lc '/usr/local/bin/bundle exec sidekiq -e production'
     ports:
       - 80:3000
     volumes:
       - ./redmine-plugins:/usr/src/redmine/plugins
 environment:
       REDMINE_DB_POSTGRES: postgres
       REDMINE_DB_USERNAME: "user"
       REDMINE_DB_PASSWORD: "pass"
       REDMINE_DB_DATABASE: "database"
       REDMINE_SECRET_KEY_BASE: "..."
       SECRET_KEY_BASE: "..."
       REDIS_URL: "redis://redis:6379/12"
       DATABASE_URL: "postgres://user:pass@database"
     restart: always
     depends_on:
       - redis
       - postgres
   redis:
     image: redis
 volumes:
       - redis-data:/var/lib/redis/data
     restart: always
volumes:
   redis-data:
```

Questions:
1. How to fix problems with start sidekiq?
2. Maybe this way is wrong. Is there another better way to start Redmine with Sidekiq in Docker?
