### ISSUE TITLE
Tab 'Repository' disappeared after I configured a git repository for the project.

### ISSUE THREAD

**Issue by joson** [docker-library/redmine#227]
Hi,
  I've enabled the repository module in both administration settings and project settings. Then the repository tab had shown in the project view, until I created a git repository for the project. Now I can't recover it.

**What I had done:**
  I had tried to integrate the redmine with my gitlab (ce 13.9.1) on the same pc. The repository built by gitaly is stored in hashed type. So I filled the repository path with '.../gitlab/data/git-data/repositories/@hashed/0xx/5xxxxx.git', and identifier with '5xxxx', and then submit. 

**What I have done for trying to resolve it :**
  Now the repository tab has disappeared and There is no any repository in the project's repositories list. 
  I can't find error log by "docker logs redmine".
  I've queried the mysql table 'repositories'. It's empty.

  Any help is appreciated.

References: [Gitlab Hashed Storage](https://docs.gitlab.com/ee/administration/repository_storage_types.html#hashed-storage)

**Comment by wglambert** [comment]
I'm not able to reproduce. In the created Project I see a "Repository" tab that is populated with the local Git repo from the instructions at: https://www.redmine.org/projects/redmine/wiki/redminerepositories#Local-environment-setup

![image](https://user-images.githubusercontent.com/26428991/109850910-e398f680-7c07-11eb-99ae-dbbbf6056ea8.png)

I used this `docker-compose.yml` and the only step I didn't have to do on that page was the `chown rails:rails` line (since we're containerized 😉)
```yaml
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```

Can you give all the commands you ran and any relevant files to help with reproducing? You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
