### ISSUE TITLE
Redmine is no longer able to start/build its dependencies

### ISSUE THREAD

**Issue by christianlupus** [docker-library/redmine#228]
I have today updated my docker container and I am no longer able to run the redmine image. Here are [the logs of the container](https://gist.github.com/christianlupus/4013f1286d905fd7a065fa033f7902f2).

I have not (knowingly) changed anything on my setup. I tried to enter a container (using `docker run`) and mimic the entrypoint to get the command `bundle install` running (which is the failing command during entrypoint). I did not succeed. Maybe you know an issue that might be triggered here.
I think there might be missing a dependency.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files (`Dockerfile`/`docker-compose.yml` etc...) for reproducing the issue

Do you have a compiler installed when building the extensions? You likely need `libc6-dev` too unless you're using Alpine in which case it'd be `musl-dev`

**Comment by Campano** [comment]
I had to install some build tools on alpine with `apk add --no-cache build-base` (I'm on a less than one-yea old 4-alpine image). Got tipped by the first problematic gem install instructions and it resolved all other problems (https://github.com/sparklemotion/nokogiri.org/blob/91e624fa8d6c918d7905954fd8da7ea40f237d88/docs/tutorials/installing_nokogiri.md#ruby-on-alpine-linux-docker ). I should probably add it to a DockerFile

```
RUN apk add --no-cache build-base
```

**Comment by christianlupus** [comment]
I at least was able to track down the problem a bit. It is caused by [a plugin](https://github.com/jperelli/Redmine-Periodic-Task/). I am not sure if this is a problem with the docker installation (aka this repository) or with the plugin's code.

<details><summary>To have an MWE, I created a new set of docker-compose files (expand here to see them).</summary>
<b>docker-compose.yml</b> (I disabled here a few lines as it is only an MWA and I do not want to interfere with the running main service)):

```
version: "3.2"

volumes:
    dbdata:
    app_plugins:

services:
    db:
        image: mariadb
        restart: always
        volumes:
            - type: volume
              target: "/var/lib/mysql"
              source: dbdata
        environment:
            MYSQL_ROOT_PASSWORD: root-secret
            MYSQL_DATABASE: redmine
            MYSQL_USER: redmine
            MYSQL_PASSWORD: password-redmine
    
    app:
        #image: redmine:passenger
        build: ./app
        image: myredmine-bugreport:rbtree
        depends_on:
            - db
        restart: unless-stopped
#        ports:
#            - "127.0.0.1:3000:3000"
        volumes:
            - type: bind
              target: /usr/src/redmine/plugins
              source: /srv/http/redmine/docker/plugins
              read_only: true
            - type: bind
              target: /usr/src/redmine/config/configuration.yml
              source: ./configuration.yml
              read_only: true
#            - type: bind
#              target: /usr/src/redmine/files
#              source: /srv/http/redmine/docker/files
        environment:
            REDMINE_DB_MYSQL: db
            REDMINE_DB_USERNAME: redmine
            REDMINE_DB_PASSWORD: password-redmine
            REDMINE_DB_DATABASE: redmine
            REDMINE_PLUGINS_MIGRATE: 1
```

<b>configuration.yml</b>:
```
default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.example.com"
      port: 587
      authentication: :login
      domain: 'example.com'
      user_name: 'redmine'
      password: 'very_confidential_secret'
```

<b>app/Dockerfile</b>
```
FROM redmine:4.0-passenger
RUN groupadd -g 196 gitolite && usermod -aG gitolite redmine
```
</details>

I then took these steps:
1. Move the plugin into a temporary folder out of the way (for testing).
1. Run `docker-compose up -d db` and wait for the DB to be initialized
2. Run `docker-compose up -d app`, keep a look at `docker-compose logs -f app`. The redmine app starts successfully and serves requests.
3. Stop the app with `docker-compose stop app` and remove container `docker-compose rm app`
4. Check out the [periodic task plugin](https://github.com/jperelli/Redmine-Periodic-Task/) into the folder `/srv/http/redmine/docker/plugins/periodic_tasks`. In my case I moved the temp files back in place and updated them to the latest version using git.
5. Run `docker-compose up -d app` and have a look at `docker-compose logs -f app`. The logs I posted in my very first post.
