### ISSUE TITLE
REDMINE_DB_PORT is not working

### ISSUE THREAD

**Issue by MarcAntoineCRUE** [docker-library/redmine#245]
Hi,

Using the variable REDMINE_DB_PORT does not have any effect.

I'm deploying a second redmine to makes some tests. Two redmine with two db (almost a simple copy of the db).

But i changed the port of the mysql on the second db, and tried to connect. but the two redmine instances are connecting to the first one (port 3306).

here is the content of my docker compose (REDMINE_VERSION=4.2) :

```
version: '3.8'
services:

  redmine:
    image: redmine:${REDMINE_VERSION}
    container_name: redmine
    restart: unless-stopped
    depends_on:
      - redmine_db
    environment:
      REDMINE_PLUGINS_MIGRATE: 1
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_DATABASE: ${MYSQL_DB_NAME}
      REDMINE_DB_USERNAME: ${MYSQL_USERNAME}
      REDMINE_DB_PASSWORD: ${MYSQL_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_TOKEN}
    volumes:
      - ./dataredmine/backup:/media/backup
      - ./dataredmine/redmine/files:/usr/src/redmine/files
      - ./dataredmine/redmine/log:/usr/src/redmine/log
      - ./dataredmine/redmine/plugins:/usr/src/redmine/plugins
      - ./dataredmine/redmine/public:/usr/src/redmine/public
      - ./dataredmine/redmine/config:/usr/src/redmine/config
    labels:
      # Network
      - traefik.enable=true
      # Https
      - traefik.http.routers.redmine.rule=Host(`redmine.${DOMAIN}`)
      - traefik.http.routers.redmine.entrypoints=websecure
      - traefik.http.routers.redmine.tls=true
      - traefik.http.routers.redmine.service=redmine
      # Loadbalancer
      - traefik.http.services.redmine.loadbalancer.server.port=3000
      # Middlewares
      - traefik.http.routers.redmine.middlewares=redmine-ssl
      - traefik.http.middlewares.redmine-ssl.headers.sslForceHost=true
      - traefik.http.middlewares.redmine-ssl.headers.sslHost=redmine.${DOMAIN}

  redmine_db:
    image: mysql:${MYSQL_VERSION}
    container_name: redmine_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dataredmine/mysql:/var/lib/mysql
      - ./dataredmine/backup:/media/backup
    labels:
      - "traefik.enable=false"



  redmine_2:
    image: redmine:${REDMINE_VERSION}
    container_name: redmine_2
    restart: unless-stopped
    depends_on:
      - redmine_db_2
    ports:
     - 3001:3000
    environment:
      REDMINE_PLUGINS_MIGRATE: 1
      REDMINE_DB_MYSQL: redmine_db_2
      REDMINE_DB_DATABASE: ${MYSQL_DB_NAME}
      REDMINE_DB_USERNAME: ${MYSQL_USERNAME}
      REDMINE_DB_PASSWORD: ${MYSQL_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_TOKEN}
      REDMINE_DB_PORT: 3307
    volumes:
      - ./dataredmine2/backup:/media/backup
      - ./dataredmine2/redmine/files:/usr/src/redmine/files
      - ./dataredmine2/redmine/log:/usr/src/redmine/log
      - ./dataredmine2/redmine/plugins:/usr/src/redmine/plugins
      - ./dataredmine2/redmine/public:/usr/src/redmine/public
      - ./dataredmine2/redmine/config:/usr/src/redmine/config

  redmine_db_2:
    image: mysql:${MYSQL_VERSION}
    container_name: redmine_db_2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./dataredmine2/mysql:/var/lib/mysql
      - ./dataredmine2/backup:/media/backup
    labels:
      - "traefik.enable=false"

networks:
  default:
    external:
      name: Services

```

The redmine and redmine_2 containers are connecting to the redmine_db both side. When I'm setting a new issue on the first instance, the issue is also present on the second redmine instance, as they are using the same db.
