### ISSUE TITLE
Lang file not updating

### ISSUE THREAD

**Issue by IvoLeal72** [docker-library/redmine#262]
I changed the pt.yml file, but the website doesn't use the updated string.
I tried making a syntax error in the file and it got detected by the 'rake locales:check_interpolation' command, which means it is getting read.
I will send an example of a string in the website and the new corrected pt.yml part.
![image](https://user-images.githubusercontent.com/62177040/164752872-addb4443-c82e-4817-9811-3eeeb3863fa3.png)

label_updated_issues: Tarefas atualizadas

**Comment by wglambert** [comment]
You might have to restart the container for it to reload files. I'm not sure if there's a way to tell it to reload while running

**Comment by IvoLeal72** [comment]
That's exactly where the problem is I tried that, "Docker restart", "docker stop"->"docker start", even restarting our machine

**Comment by wglambert** [comment]
I'm not able to reproduce with a `docker restart` on the redmine container

docker-compose.yml
```yaml
version: '3.1'
services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: pass
    volumes:
      - ./en.yml:/usr/src/redmine/config/locales/en.yml
      - ./files:/usr/src/redmine/files
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: redmine
    volumes:
      - ./postgres:/var/lib/postgresql/data
```
```console
$ docker-compose up -d
Creating network "redmine_default" with the default driver
Creating redmine_redmine_1 ... done
Creating redmine_db_1      ... done
```

I changed the `field_digest: Checksum` to be `field_digest: Test Change`. Before it looks like 
![image](https://user-images.githubusercontent.com/26428991/164779245-a04ef613-9435-40bb-94d3-b24e988ac09d.png)

Then I edit the bind-mounted file and restart the redmine container
```console
$ docker restart redmine_redmine_1
redmine_redmine_1
```

![image](https://user-images.githubusercontent.com/26428991/164779622-3a0e262b-491e-4aca-b964-4ba0a925be6f.png)



You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
