### ISSUE TITLE
docker redmine:latest email notification broken

### ISSUE THREAD

**Issue by Iceforestik** [docker-library/redmine#265]
after launching with the new image, email newsletters do not work, there is an ssl certificate error in the logs, on the redmine version:4.2.6 this error did not occur and notifications were sent

`, [2022-05-20T12:52:20.356575 #1] ERROR -- : Email delivery error: SSL_connect returned=1 errno=0 peeraddr=**ipaddress**:465 state=error: certificate verify failed (unable to get local issuer certificate)`

configuration.yml:

```
production:
  email_delivery:
      delivery_method: :smtp
      smtp_settings:
        enable_starttls_auto: true
        tls: true
        address: "*****"
        port: 465
        domain: '*****'
        authentication: :login
        user_name: ****'
        password: '****'
```

**Comment by wglambert** [comment]
I'm not able to reproduce the issue using a test email on a gmail account. The `configuration.yml` is the same template

```console
$ docker run -d -v "$PWD"/configuration.yml:/usr/src/redmine/config/configuration.yml -p 3000:3000 --rm --name redmine redmine:4.2.6
76bb937f8506d86d2a5cf6345d1359de9938b6c2432d8fdad8897b1748cc6777
```
Change the user email to the gmail and then send a test

![image](https://user-images.githubusercontent.com/26428991/169575560-ffae18cb-6c63-433f-8892-6ebcdfc8669e.png)

I did have to enable insecure auth (there's also some new app-password feature replacing this in a week) and then disable the captcha for login https://accounts.google.com/b/0/DisplayUnlockCaptcha

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

**Comment by coldib** [comment]
I have exactly the same issue starting on Redmine 5.0.1

**Comment by Iceforestik** [comment]
> I have exactly the same issue starting on Redmine 5.0.1

I resolved this problem, I add two changes

```
production:

  email_delivery:
      delivery_method: :smtp
  smtp_settings:
        enable_starttls_auto: true
        tls: true
        openssl_verify_mode: "NONE"
        address: "address"
        port: 465
        domain: 'domain'
        authentication: :plain
        user_name: 'email '
        password: 'Password '
```
