### ISSUE TITLE
When sending emails, emails are not sent. I see an error in the logs.

### ISSUE THREAD

**Issue by MrKira34** [docker-library/redmine#281]
I am running redmine in docker:

docker-compose.yml
```
version: "2.1"

services:
    redmine:
        container_name: ruby-redmine
        restart: always
        build:
            context: ./src-ruby-2.3
            dockerfile: Dockerfile
        volumes:
          - "./code:/src"
        ports:
          - "127.0.0.1:3000:3000"
```

Dockerfile:
```
FROM centos:7
RUN yum update -y && yum install curl gnupg2 ca-certificates lsb-release -y
RUN yum install which -y
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import -  && curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
#RUN curl -sSL https://get.rvm.io | bash -s stable
#RUN cd /usr/local/rvm && bin/rvm install ruby-2.3.0
RUN yum install libmysqlclient-dev ImageMagick libmagickwand-dev libssl-dev openssl -y
RUN yum install ImageMagick ImageMagick-devel svn cvs bzr hg darcs -y
RUN yum install git nano wget -y
RUN rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
RUN yum localinstall https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm -y
RUN yum install mysql-community-client mysql-community-devel mysql-community-libs-compat -y
RUN curl -sSL https://get.rvm.io | bash -s stable
RUN cd /usr/local/rvm && bin/rvm install ruby-2.3.2
ADD ./run.sh /root/run.sh
CMD /bin/bash /root/run.sh
```

run.sh
```
source /etc/profile.d/rvm.sh
rvm --default use ruby-2.3.2
cd /src/
rm -f Gemfile.lock
gem install --default bundler -v 1.17.3
bundle config git.allow_insecure true
bundle config github.https true
bundle config set --local without 'development test postgresql sqlite'
gem install rdoc-data
gem install openssl -v 2.2.2
bundle install 
bundle exec rails server webrick -e production  -p 3000 -b 0.0.0.0 -P /tmp/server.pid
while [ 1 ]; do
   sleep 10;
done
```

configuration.yml
```
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      tls: true
      address: "smtp.yandex.ru"
      port: 465
      authentication: "plain"
      domain: "domain.ru"
#      authentication: :login
      user_name: "redmine@domail.ru"
      password: "password"
#      enable_starttls_auto: true
#      openssl_verify_mode: true

```

log
```
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"/vksEOz1nhY6h2oFVK/mgSd85MfnIgjd8wPr2b3LVSdDGBK4gBtHRwiGFvBim071VRTO+GTyfoZKfr8jOE/rg==", "user"=>{"firstname"=>"Павел", "lastname"=>"Зоммер", "mail"=>niraj@altspu.ru", "language"=>"ru", "custom_field_values"=>{"35"=>"Администратор"}, "mail_notification"=>"only_my_events", "notified_project_ids"=>[""]}, "pref"=>{"favourite_project_id"=>"", "no_self_notified"=>"1", "hide_mail"=>"0", "time_zone"=>"Moscow", "comments_sorting"=>"asc", "warn_on_leaving_unsaved"=>"1", "textarea_font"=>"", "landing_page"=>"", "autowatch_involved_issue"=>"1"}, "commit"=>"Сохранить"}
  Current user: p.zommer (id=164)
  Rendered mailer/security_notification.text.erb within layouts/mailer (4.3ms)
  Rendered mailer/security_notification.html.erb within layouts/mailer (1.8ms)
Email delivery error: no implicit conversion of true into Integer
Redirected to http://redmine/my/account
Completed 302 Found in 619ms (ActiveRecord: 24.6ms)
--
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"CqXf0wi4prD4ZbVTcZhfusDhKurDNwX+3G7tSIsdZoC3ROF7ZFZ/4cpkyaZHrPfOsEdFsWGxNk2RPxtujcMCQ==", "user"=>{"firstname"=>"Павел", "lastname"=>"Зоммер", "mail"=>niraj@altspu.ru", "language"=>"ru", "custom_field_values"=>{"35"=>"Администратор"}, "mail_notification"=>"only_my_events", "notified_project_ids"=>[""]}, "pref"=>{"favourite_project_id"=>"", "no_self_notified"=>"1", "hide_mail"=>"0", "time_zone"=>"Moscow", "comments_sorting"=>"asc", "warn_on_leaving_unsaved"=>"1", "textarea_font"=>"", "landing_page"=>"", "autowatch_involved_issue"=>"1"}, "commit"=>"Сохранить"}
  Current user: p.zommer (id=164)
  Rendered mailer/security_notification.text.erb within layouts/mailer (3.6ms)
  Rendered mailer/security_notification.html.erb within layouts/mailer (1.7ms)
Email delivery error: undefined method `ssl_socket_connect' for #<Net::SMTP smtp.yandex.ru:587 started=false>
Redirected to http://redmine/my/account
Completed 302 Found in 582ms (ActiveRecord: 30.1ms)
```

`Email delivery error: undefined method `ssl_socket_connect' for #<Net::SMTP smtp.yandex.ru:465 started=false>`
