### ISSUE TITLE
Specify SMTP settings through ENV_VARS

### ISSUE THREAD

**Issue by regentov** [docker-library/redmine#297]
The redmine that is run through this image cannot send any emails:

![изображение](https://github.com/docker-library/redmine/assets/26378677/60de2a87-430f-4353-ab57-a9a07d495f22)

This image's docker-entrypoint.sh should be able to generate config/configuration.yml with at least simple plain-smtp settings if env settings are set.

E.g.

```
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: $SMTP_ADDRESS
      port: $SMTP_PORT
      domain: $SMTP_DOMAIN
```
