### ISSUE TITLE
Image for Redmine 5.1

### ISSUE THREAD

**Issue by smap9** [docker-library/redmine#303]
Redmine 5.1 was released last week. https://www.redmine.org/news/142

Can you create an image for this version?

**Comment by achernyakevich-sc** [comment]
@tianon Just to be sure - is support for Redmine 5.1.x takes into account changes to `database.yml` that need to be applied to work correct with MySQL?

See https://www.redmine.org/projects/redmine/wiki/MySQL_configuration for more information.

**Comment by yosifkit** [comment]
The `docker-entrypoint.sh` is currently unchanged. Even if we changed it, it wouldn't affect users that upgrade from one version to another (since they already have a `database.yml`). I'd suggest setting `transaction_isolation="READ-COMMITTED"` on the MySQL server. So this should be a documentation change for the Docker Hub page.

Users can add it right into thier [compose yaml](https://github.com/docker-library/docs/tree/126cb27683548a54245b4badfb7a3856a04a6c75/redmine#-via-docker-compose-or-docker-stack-deploy):
```yaml
version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
#####
    command: --transaction_isolation=READ-COMMITTED
#####
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```
