### ISSUE TITLE
Failed check after upgrade to Redmine 5.1.1

### ISSUE THREAD

**Issue by pavel-francirek** [docker-library/redmine#312]
After upgrade to latest image there is failed check in admin/info section:

"Default queue adapter which is well suited only for dev/test changed" -  NO

Running it with simple docker-compose:
```
version: '2'

services:

  redmine:
    image: redmine
    ports:
      - 127.0.0.1:8080:3000
    environment:
      POSTGRES_ENV_POSTGRES_USER: xxx
      POSTGRES_ENV_POSTGRES_PASSWORD: xxx
      REDMINE_DB_POSTGRES: 123.456.789.012
    volumes:
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./datadir:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
    restart: always
    logging:
      options:
        max-size: 10m
 ```
