### ISSUE TITLE
Wrong connection when use external container (MySQL)

### ISSUE THREAD

**Issue by vasintalana** [docker-library/redmine#32]
Hi,
I want redmine to connect to mysql (172.17.0.2)
But turned out to 172.17.0.3
`Mysql2::Error: Access denied for user 'redmine'@'172.17.0.3' (using password: YES)`

When I check
docker exec -it redmine cat /usr/src/redmine/config/database.yml

The configuration seems right

```
production:
  adapter: "mysql2"
  host: "172.17.0.2"
  port: "3306"
  username: "redmine"
  password: "secret"
  database: "redmine"
```

This is what I use in `docker-compose.yml`

```
version: '2.0'
services:
  redmine:
    container_name: redmine
    environment:
      REDMINE_DB_MYSQL: 172.17.0.2
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: secret
      REDMINE_DB_DATABASE: redmine
    external_links:
    - mariadb
    image: redmine:3.3
    network_mode: bridge
    ports:
    - 8083:3000
    restart: always
    volumes:
    - /srv/divusi_redmine/files:/usr/src/redmine/files:rw
```

And I've created a database
Is there a solution?
