### ISSUE TITLE
Allow 'instance' parameter in database.yml to be set via environment variable

### ISSUE THREAD

**Issue by buhlmann-thomas-rix** [docker-library/redmine#325]
When using MS SQL Server with a named instance as database server, it is required to set the name of the instance in the `instance` parameter in `config/database.yml`. Using `sql-server-host\instance_name` for `host` parameter does not work.

Please introduce a new environment variable, e.g. `REDMINE_DB_SQLSERVER_INSTANCE`, that allows setting the name of the database instance to connect to.

Currently, I created a workaround by exporting the `config/database.yml` file via a Docker volume to my local filesystem and altering its contents manually. But this should not be the official way doing this.

Working example:
```
production:
  adapter: "sqlserver"
  host: "sql-server-host"
  instance: "instance_name"
  port: "61602"
  username: "sql-username"
  password: "super-secret-sql-password"
  database: "REDMINE"
  encoding: "utf-8"
```
