### ISSUE TITLE
Unknown database adapter "mysql2" found in config/database.yml

### ISSUE THREAD

**Issue by charlesmulder** [docker-library/redmine#354]
Hi

I'm getting the following mysql2 gem related error when running Redmine via docker compose. 

I've searched the issues, but couldn't find anything. I must be missing something obvious. Any advice is much appreciated.

Thank you.

```
Unknown database adapter `"mysql2"` found in config/database.yml, use Gemfile.local to load your own database gems
redmine-1  | rake aborted!
redmine-1  | LoadError: Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? mysql2 is not part of the bundle. Add it to your Gemfile. (LoadError)
```

Here is my `docker-compose.yaml` file. 

```
services:                                                                                                                                                  
                                                                                                                                                           
  redmine:                                                                                                                                                 
    image: redmine:6                                                                                                                                       
    ports:                                                                                                                                                 
      - 8080:3000                                                                                                                                          
    environment:                                                                                                                                           
      REDMINE_DB_MYSQL: db                                                                                                                                 
      REDMINE_DB_USERNAME: redmine                                                                                                                         
      REDMINE_DB_PASSWORD: secret                                                                                                                          
      REDMINE_SECRET_KEY_BASE: supersecret                                                                                                                 
                                                                                                                                                           
  db:                                                                                                                                                      
    image: mysql:8.0                                                                                                                                       
    environment:                                                                                                                                           
      MYSQL_DATABASE: redmine                                                                                                                              
      MYSQL_USER: redmine                                                                                                                                  
      MYSQL_PASSWORD: secret                                                                                                                               
      MYSQL_ALLOW_EMPTY_PASSWORD: true
```

**Comment by hempalex** [comment]
Same error after pulling redmine:6.0.2

My docker-compose.yml

```
  redmine:
    image: redmine:6
    depends_on:
      - redmine-db
    ports:
     3000:3000
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_USERNAME: ${MYSQL_USER}
      REDMINE_DB_PASSWORD: ${MYSQL_PASSWORD}
      REDMINE_DB_DATABASE: ${MYSQL_DATABASE}
      REDMINE_PLUGINS_MIGRATE: true

  redmine-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

```
