### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by kilass** [docker-library/redmine#37]
Hi,

I'm encountering a bit of trouble trying to add some plugins on my redmine container. 
I've mounted a volume on my host to the plugin directory on the redmine container, and launched it. 
Here is the command i use to launch my database container: 
`docker run -d --name redmine-db -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=redmine postgres`
And the one i use to start my redmine container: 
`docker run -d --name redmine --link redmine-db:postgres -p 3000:3000 -v /home/apside/docker/redmine/files:/usr/src/redmine/files -v /home/apside/docker/redmine/plugins:/usr/src/redmine/plugins redmine`
But i'm always getting the same write access error on the Gemfile.lock, as `bundle install` is run as root.
Here is the log i'm facing for hours with no ideas on how to resolve it: 

> /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:107:in `rescue in filesystem_access': There was an error while trying to write to`/usr/src/redmine/Gemfile.lock`. It is likely that you need to grant write permissions for that path. (Bundler::PermissionError)

Is there any workaround ? Any ideas of what am I doing wrong ? 
I'm used to work with ruby and rails, and have already faced those kind of issues. Mainly, you've got those kind of errors, when you try running bundle install as root. But, working inside a docker container, i have no real choices about it.

I've also tried running my container with the `--user redmine` as an argument, but got another write acces error, before it can access the right directory....

I'm totally stuck at this point... Any ideas ?

**Comment by imaia** [comment]
Suggestion: do not mount the plugins directory. You can also use gosu to run a command as the redmine user. I'm also not fond of not running the container as an unprivileged user.

**Comment by tiryu** [comment]
Hi, did you find any solution to install plugin on your redmine container ?

Actually, i just mount a volume on plugins dir and add it manually, connect to the container redmine and execute the commands (redmine_agile plugin for example) : 

```
bundle install --without development test --no-deployment
bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
```

I tried this in the docker-compose : 

```
command:
      - /bin/sh
      - -c
      - |
         bundle exec rake tmp:cache:clear tmp:sessions:clear RAILS_ENV=production
         bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
         /docker-entrypoint.sh passenger start
```
         
But i got an error on /usr/src/redmine/db/schema.rb : 

> Errno::EACCES: Permission denied @ rb_sysopen

I can see there is a rights problem on the file, but it seems to exist only when docker-entrypoint.sh is executed.

**Comment by yosifkit** [comment]
@tiryu, the entrypoint script drops down from root to the redmine user when it starts passenger (after it creates the `config/database.yml` and ensures the `db:migrate` is run); most likely your two rakes create a file as root and then the passenger process cannot access it.  I think the easiest solution is to just prefix your commands with the entrypoint. Any `rake` [task](https://github.com/docker-library/redmine/blob/b994741065b7a297d030b7826c478655a10f26bd/docker-entrypoint.sh#L27) will ensure the database.yml exists and then [drop to the correct user](https://github.com/docker-library/redmine/blob/b994741065b7a297d030b7826c478655a10f26bd/docker-entrypoint.sh#L122) for the task.

```yaml
# not sure on moving RAILS_ENV to an environment variable, but I was assuming it would be needed for passenger as well
    environment:
      - RAILS_ENV=production
    command:
      - /bin/sh
      - -ec
      - |
         /docker-entrypoint.sh rake tmp:cache:clear tmp:sessions:clear
         /docker-entrypoint.sh rake redmine:plugins NAME=redmine_agile
         /docker-entrypoint.sh passenger start
```

You could also just use `gosu` to ensure it is the proper user `gosu redmine rake tmp:cache:clear tmp:sessions:clear`

**Comment by tiryu** [comment]
@yosifkit I've got an issue about this.

I can do that only if i ran once time at least, the image with no list of commands. Passenger has to start alone to init creation and migrate tables needed for redmine. And after, i can change my compose with the list of commands you said.

If i want the process of the entrypoint to create normally the database.yml, I need to declare in environment section of compose : POSTGRES_ENV_POSTGRES_USER to set the good user.

The variable REDMINE_DB_USER seems not to be sufficient (cause error launched by container db : postgres user is used by default)

Maybe you have an idea on these ?

**Comment by yosifkit** [comment]
Quick addition on my previous command so that you don't have to run it once with no `CMD`.

```yaml
# not sure on moving RAILS_ENV to an environment variable, but I was assuming it would be needed for passenger as well
    environment:
      - RAILS_ENV=production
    command:
      - /bin/sh
      - -ec
      - |
         /docker-entrypoint.sh rake db:migrate
         /docker-entrypoint.sh rake tmp:cache:clear tmp:sessions:clear
         /docker-entrypoint.sh rake redmine:plugins NAME=redmine_agile
         /docker-entrypoint.sh passenger start
```
