### ISSUE TITLE
'links' in docker-compose.yml doesn't work.

### ISSUE THREAD

**Issue by hanlz** [docker-library/redmine#40]
I followed the instructions in READ.md by executing 'docker run', and it works. Then I wrote a compose file like this:

```
version: '2'

services:

  mysql:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $RMPASS
      MYSQL_DATABASE: $RMDB

  redmine:
    image: redmine
    restart: always
    links:
      - mysql
```

while I run `docker-compose up`, I got message of redmine below:

> warning: missing REDMINE_DB_MYSQL or REDMINE_DB_POSTGRES environment variables
> 
> **\* Using sqlite3 as fallback. ***

It's build on sqlite, which is not my purpose. Can anybody help? I would so appreciate with this.
