### ISSUE TITLE
Not clear how to use redmine with postgresql

### ISSUE THREAD

**Issue by lukjel** [docker-library/redmine#41]
This is not clear how to start redmine with postgresql. I expect some example which should look like:

docker run --name=redmine-production -d \
  --network postgresnetwork \
  --env='POSTGRESQL_HOST=postgres' \
  --env='POSTGRESQL_DB_NAME=redmine_production' \
  --env='POSTGRESQL_USER=redmine'
  --env='POSTGRESQL_PASS=password' \
  --volume=/home/docker/redmine_production/redmine:/home/redmine/data \
  redmine

(this is clear example taken from sameersbn/redmine)

compose.yml is ok, but it shows only MYSQL variable name - there is no info about POSTGRESQL names.

**Comment by abcfy2** [comment]
Here is my `docker-compose.yml`, you can check it out:
```yaml
version: '2'
services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    logging:
      options:
        max-size: "100k"
        max-file: "2"

  redmine:
    image: redmine:passenger
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
    volumes:
      - ./redmine_storage/files/:/usr/src/redmine/files/
      - ./redmine_storage/plugins/:/usr/src/redmine/plugins/
      - ./redmine_storage/public/themes/:/usr/src/redmine/public/themes/
      - ./redmine_storage/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    command:
      - /bin/sh
      - -c
      - |
          bundle config mirror.https://rubygems.org https://gems.ruby-china.org
          bundle exec rake redmine:plugins:migrate RAILS_ENV=production
          /docker-entrypoint.sh passenger start
    logging:
      options:
        max-size: "100k"
        max-file: "2"
```

./docker-entrypoint-initdb.d/init-user-db.sh:
```bash
#!/bin/sh -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER redmine LOGIN PASSWORD 'redmine';
    CREATE DATABASE redmine OWNER redmine;
EOSQL
```
