### ISSUE TITLE
X_FORWARDED_PROTO https

### ISSUE THREAD

**Issue by siochs** [docker-library/redmine#60]
Hi There, 
my setup looks as following:
https --> apache reverse proxy, ssl offloading --> http --> redmine container
When calling https://myserver/ I get the first login page of redmine. So far so good. But when submitting the credentials, it seems that I am getting redirected to http://myserver/my/page. My apache reverse proxy has no http configured so i get an error response.
In my apache reverse proxy configuration I added the following line: `RequestHeader set X_FORWARDED_PROTO 'https'`. However, this has no effect. I think that the webserver in the redmine container should be configured to set `X_FORWARDED_PROTO 'https'` as well? If yes, how can I do this?
This is my docker-compose.yml file:
``` 
version: '2'
services:
  webapp:
    image: redmine:3.3.2-passenger
    ports:
      - 3001:3000
    volumes:
      - files:/usr/src/redmine/files
      - /local/redmine/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: secret-db-root-pw
    depends_on:
      - db
    restart: on-failure:10

  db:
    image: mariadb:10.1
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret-db-root-pw
      MYSQL_DATABASE: redmine
    restart: on-failure:10

volumes:
  db:
  files:
```
