### ISSUE TITLE
docker-entrypoint.sh and config/database.yml

### ISSUE THREAD

**Issue by tiryu** [docker-library/redmine#61]
Hello,

Actually i've got a problem when i try to launch an official image redmine:3.3.3 with my compose file.

The container redmine send me an error with this message : 

 `/docker-entrypoint.sh: line 75: config/database.yml: No such file or directory`

Here my docker-compose : 

```

version: '2'

services:

  redmine:
    image: redmine:${REDMINE_VERSION}
    container_name: redmine
    ports:
      - 8081:3000
    environment:
      - REDMINE_DB_POSTGRES=${DB_NAME_REDMINE}
      - POSTGRES_ENV_POSTGRES_USER=${DB_USER_REDMINE}
      - POSTGRES_ENV_PASSWORD=${DB_PASSWORD_REDMINE}
    volumes:
      - /src/redmine/:/usr/src/redmine:Z
    links:
      - db
    restart: always

  db:
    image: postgres:${DB_VERSION_REDMINE}
    container_name: redmine_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD_REDMINE}
      - POSTGRES_DB=${DB_NAME_REDMINE}
      - POSTGRES_USER=${DB_USER_REDMINE}
    volumes:
      - /src/redmine/postgresql:/var/lib/postgresql:Z
    restart: always

```

Do i need to recreate a dockerfile based on the official image and add a COPY of database.yml to /usr/src/redmine/config ?

Thanks!

**Comment by yosifkit** [comment]
No, that file will be automatically created by the entrypoint. The problem is that the config directory does not exist; which is caused by mounting a folder (volume) on `/usr/src/redmine`. It should be [`/usr/src/redmine/files`](https://github.com/docker-library/redmine/blob/b994741065b7a297d030b7826c478655a10f26bd/3.3/Dockerfile#L84), otherwise you will be hiding the entire install of redmine.

A few other tweaks:

```yaml
version: '2'

services:

  redmine:
    image: redmine:${REDMINE_VERSION}
    container_name: redmine
    ports:
      - 8081:3000
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_DATABASE=${DB_NAME_REDMINE}
      - REDMINE_DB_USER=${DB_USER_REDMINE}
      - REDMINE_DB_PASSWORD=${DB_PASSWORD_REDMINE}
    volumes:
      - /src/redmine/:/usr/src/redmine/files/:Z
    links:
      - db
    restart: always
...

```
