### ISSUE TITLE
database.yml-file not always created, puzzled

### ISSUE THREAD

**Issue by Inkimar** [docker-library/redmine#62]
Hello,

building a redmine-image 'on-top-of-yours' , and it looks like this:

**My Dockerfile** : dina/redmine:v02
-copying in some themes and plugins
-create a directory : 
RUN mkdir -p \
/usr/src/redmine/mail-script 
-some other things

**My docker-compose.yml**
```
version: '2'
services:

  redmine:
    image: dina/redmine:v02
    container_name: redmine_inki
    environment:
      - VIRTUAL_HOST=support.dina-web.net
      - REDMINE_DB_MYSQL=mariadb_redmine
      - REDMINE_DB_PASSWORD=secr3t
    volumes:
      - ./redmine-mail_config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./redmine-harvest/.env:/usr/src/redmine/mail-script/.env
      - ./redmine-harvest/receive_imap.sh:/usr/src/redmine/mail-script/receive_imap.sh
      - ./redmine-files:/usr/src/redmine/files
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.1
    container_name: mariadb_redmine
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: secr3t
    volumes:
      - ./redminedb-init.d:/docker-entrypoint-initdb.d
    restart: always
```
From time and again, did not see any pattern - the database.yml-file is not created.
I removed the maridb:10.1 image and started over and the database.yml-file was created.
- what is causing this behavior ? and how can a guarantee that the database.yml-file is always created ?

best regards, i
