### ISSUE TITLE
nginx location with redmine passenger

### ISSUE THREAD

**Issue by tiryu** [docker-library/redmine#67]
Hello,

I've got an issue running redmine-passenger with nginx in an other container.

Here's a part of my docker-compose file : 

 ```
 nginx:
    image: nginx
    container_name: nginx-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    links:
      - redmine-web

 redmine-db:
 ...

redmine-web:
    image: redmine:3.3.3-passenger
    container_name: redmine-web
    build:
      context: ./redmine/compose
    ports:
      - 8081:3000
....
```

Here's configuration of my nginx.conf : 

```
http {
        error_log /var/log/nginx/error.log warn;
        access_log  /dev/null;
        proxy_intercept_errors off;
        proxy_send_timeout 120;
        proxy_read_timeout 300;

        #Redmine
        upstream redmine {
        server redmine-web:3000;
        }


        server {
        listen 80;
        server_name localhost;


        keepalive_timeout  5 5;
        proxy_buffering    off;

        # allow large uploads
        client_max_body_size 1G;

        location /redmine/ {
                proxy_pass http://redmine;
        }
    }
```

When I try to access http://$IP/redmine, i have the page displayed but not the style, js etc...did i miss some configuration anywhere ?

**Comment by yosifkit** [comment]
It looks like you need to set some config in redmine.

>And to have the links and CSS work on a connection over the proxy server I had to add the following to redmine/config/environment.rb:
>
>  config.action_controller.relative_url_root = '/redmine'
>
> \- https://www.redmine.org/boards/2/topics/27570

**Comment by tiryu** [comment]
@yosifkit thanks for your answer, but i still one issue :)

First, the good file to modify was config/application.rb or config/environments/production.rb (or development), to add the line ( config.action_controller.relative_url_root = '/redmine').

I said "good" because I already tried to modify the config/environment.rb but nothing seems to work on it (error : no routes matched on /redmine)

I had to modify my nginx.conf adding a slash to my server in location and had what the guy said on his update statement : 

```
proxy_pass http://redmine/;
 proxy_set_header X-Forwarded-Proto https
```

If i click on Projects menu, it's going to http://$IP/projects instead of http://$IP/redmine/projects.
It seems the proxy doesn't work good.

Any idea ?

**Comment by brockbackups** [comment]
I am having the same issue with the css and js files. My docker-compose.yml:
`version: "2"

services:

  redmine_db:
    image: mysql
    restart: always
    volumes:
      - ./volumes/db/redmine_db/data:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=redmine
      - MYSQL_DATABASE=redmine
      - MYSQL_PASSWORD=password

  redmine_app:
    image: redmine
    restart: always
    volumes:
      - ./volumes/app/redmine/environment.rb:/usr/src/redmine/config/environment.rb:ro
      - ./volumes/app/redmine/data:/usr/src/redmine/files:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDMINE_DB_MYSQL=redmine_db
      - REDMINE_DB_PORT=3306
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=password
      - REDMINE_DB_DATABASE=redmine
    depends_on:
      - redmine_db

  nginx:
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./volumes/web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/web/cert/cert.crt:/etc/nginx/cert.crt:ro
      - ./volumes/web/cert/cert.key:/etc/nginx/cert.key:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redmine_app
`
My nginx.conf:
`
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
    server {
            #listen 80;
            listen 443 ssl http2;
            listen [::]:443 ssl http2;
            root /usr/src/redmine/public;

            ssl on;
            ssl_certificate /etc/nginx/cert.crt;
            ssl_certificate_key  /etc/nginx/cert.key;
            ssl_session_timeout 5m;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
            ssl_prefer_server_ciphers on;

            #Change to what you name your app container and make sure to use this as the ROOT_URL in that app
            location /redmine {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            #Change to match you container addresses and ports
            proxy_pass http://c2_redmine_app_1:3000/redmine/;
            proxy_set_header X-Forwarded-Ssl on;
     }
    }
}
`
and my environment.rb file:
`# Load the Rails application
require File.expand_path('../application', __FILE__)

# Make sure there's no plugin in vendor/plugin before starting
vendor_plugins_dir = File.join(Rails.root, "vendor", "plugins")
if Dir.glob(File.join(vendor_plugins_dir, "*")).any?
  $stderr.puts "Plugins in vendor/plugins (#{vendor_plugins_dir}) are no longer allowed. " +
    "Please, put your Redmine plugins in the `plugins` directory at the root of your " +
    "Redmine directory (#{File.join(Rails.root, "plugins")})"
  exit 1
end
RedmineApp::Application.routes.default_scope = "/redmine"
# Initialize the Rails application
Rails.application.initialize!
ActionController::Base.relative_url_root = "/redmine"
`
Same as above the https://remine_app/redmine works but the layout looks like this:
![screenshot 2017-05-22 22 27 14](https://cloud.githubusercontent.com/assets/2133029/26336024/fa018e6a-3f3d-11e7-8bcf-6cc71d695026.png)

**Comment by tiryu** [comment]
@brockbackups Hello, did you find anything since you posted here ?

**Comment by brockbackups** [comment]
I have not

**Comment by CondormanFr** [comment]
Same issue. Any answers ?

**Comment by CondormanFr** [comment]
Found answer here : https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#sub_uri_deployment_uri_fix


and a way to fix it :   

Simple trick : cd /var/www/redmine/public/ && mkdir redmine && cd redmine/ && ln -sf ../javascripts javascripts && ln -sf ../stylesheets stylesheets && ln -sf ../images images .   and other folders too.

**Comment by maximkrusina** [comment]
Maybe this will help someone - this is a piece of our production Redmine server. We have also GitLab, Portainer and other stuff in the same `docker-compose.yml` if someone is interested. And don't forget so setup correct `.env` file.

**docker-compose.yml**
```
version: '3.3'

services:



# NGINX proxy ##################################################################

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/nginx-proxy/ssl:/etc/nginx/certs
      - ./data/nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ./data/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx-proxy/challenge:/usr/share/nginx/html



# NGINX proxy letsencrypt companion ############################################

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/nginx-proxy/ssl:/etc/nginx/certs
      - ./data/nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ./data/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx-proxy/challenge:/usr/share/nginx/html
    depends_on:
      - proxy



# Redmine ######################################################################

  redmine:
    image: redmine:3.4-passenger
    container_name: redmine
    restart: always
    environment:
      - VIRTUAL_HOST=${REDMINE_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${REDMINE_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - REDMINE_DB_MYSQL=redmine-db
      - REDMINE_DB_PASSWORD=***
      - REDMINE_PLUGINS_MIGRATE=1
    expose:
      - 3000
    volumes:
      - ./data/redmine/plugins:/usr/src/redmine/plugins
      - ./data/redmine/themes:/usr/src/redmine/public/themes
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    depends_on:
      - redmine-db


  redmine-db:
    image: mariadb
    container_name: redmine-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_DATABASE=redmine
    volumes:
      - ./data/redmine-db:/var/lib/mysql
```

**.env**
```
REDMINE_HOST=red.example.com
LETSENCRYPT_EMAIL=me@example.com
```
