### ISSUE TITLE
redmine container is inaccessible

### ISSUE THREAD

**Issue by Richard-Payne** [docker-library/redmine#73]
I'm using it using the following docker-compose.yml:

```yaml
version: '2'

services:
    redmine:
        image: redmine
        container_name: project
        restart: always
        ports:
          - "8056:3000"
        environment:
          - "REDMINE_DB_MYSQL:db"
          - "REDMINE_DB_PORT:3306"
          - "REDMINE_DB_USERNAME:redmine"
          - "REDMINE_DB_PASSWORD:*****************************"
          - "REDMINE_DB_DATABASE:redmine"
          - "REDMINE_NO_DB_MIGRATE: true"
        networks:
          - web
          - db

networks:
    web:    
        external: true
    db:
        external: true
```

The container logs appear to indicate a successful start:

```console
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 12.0.0
Using i18n 0.7.0
Using json 1.8.6
Using minitest 5.10.2
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.8
Using mime-types-data 3.2016.0521
Using arel 6.0.4
Using thor 0.19.4
Using concurrent-ruby 1.0.5
Using bundler 1.15.1
Using coderay 1.1.1
Using request_store 1.0.5
Using public_suffix 2.0.5
Using mimemagic 0.3.2
Using htmlentities 4.3.4
Using rbpdf-font 1.19.1
Using net-ldap 0.12.1
Using ruby-openid 2.3.0
Using rmagick 2.16.0
Using redcarpet 3.3.4
Using sqlite3 1.3.13
Using tzinfo 1.2.3
Using nokogiri 1.6.8.1
Using rack-test 0.6.3
Using mime-types 3.1
Using sprockets 3.7.1
Using addressable 2.5.1
Using rbpdf 1.19.2
Using rack-openid 1.4.2
Using activesupport 4.2.7.1
Using loofah 2.0.3
Using mail 2.6.5
Using css_parser 1.4.10
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.4.0
Using activemodel 4.2.7.1
Using rails-html-sanitizer 1.0.3
Using roadie 3.2.1
Using rails-dom-testing 1.0.8
Using activejob 4.2.7.1
Using activerecord 4.2.7.1
Using protected_attributes 1.1.4
Using actionview 4.2.7.1
Using actionpack 4.2.7.1
Using actionmailer 4.2.7.1
Using railties 4.2.7.1
Using sprockets-rails 3.2.0
Using actionpack-action_caching 1.2.0
Using actionpack-xml_parser 1.0.2
Using jquery-rails 3.1.4
Using roadie-rails 1.2.1
Using rails 4.2.7.1
Bundle complete! 33 Gemfile dependencies, 56 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into /usr/local/bundle.
[2017-06-03 19:44:16] INFO  WEBrick 1.3.1
[2017-06-03 19:44:16] INFO  ruby 2.2.7 (2017-03-28) [x86_64-linux]
[2017-06-03 19:44:16] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
```

However, accessing the server on port 8056 results in "Connection refused", both using Chrome from my desktop's browser and using wget on the docker host.

Any ideas?

**Comment by yosifkit** [comment]
Are you on Windows or a Mac using docker-toolbox?  Then you'll need to hit the VM ip and not `localhost`.

**Comment by Richard-Payne** [comment]
Sorry, this project got sidelined and I forgot about this.  No, it's a Ubuntu 14.04 system.

**Comment by rishisun** [comment]
Hello Richard,
Is it ok to keep the "" while assigning the port
services:
    redmine:
        image: redmine
        container_name: project
        restart: always
        ports:
          - "8056:3000"

I am kind a new so.. try it with out the double colums.

rishi

**Comment by tianon** [comment]
The quotes around the ports should be fine -- I think one issue with the OP's `docker-compose.yml` is the syntax for `environment:`, which is mixing the array syntax with the object syntax, and needs to choose one or the other, ala:

```yml
        environment:
          REDMINE_DB_MYSQL: db
          REDMINE_DB_PORT: 3306
          REDMINE_DB_USERNAME: redmine
          REDMINE_DB_PASSWORD: "*****************************"
          REDMINE_DB_DATABASE: redmine
          REDMINE_NO_DB_MIGRATE: true
```
```yml
        environment:
          - "REDMINE_DB_MYSQL=db"
          - "REDMINE_DB_PORT=3306"
          - "REDMINE_DB_USERNAME=redmine"
          - "REDMINE_DB_PASSWORD=*****************************"
          - "REDMINE_DB_DATABASE=redmine"
          - "REDMINE_NO_DB_MIGRATE=true"
```

**Comment by maximkrusina** [comment]
I suggest using consistent YAML config, as suggested above.
Maybe it help, there is sample cut from our production server:

```
version: '3.3'

services:

redmine:
  image: redmine:3.4-passenger
  container_name: redmine
  restart: always
  environment:
    - REDMINE_DB_MYSQL=redmine-db
    - REDMINE_DB_PASSWORD=***
    - REDMINE_PLUGINS_MIGRATE=1
  expose:
    - 3000
  volumes:
    - ./data/redmine/plugins:/usr/src/redmine/plugins
    - ./data/redmine/themes:/usr/src/redmine/public/themes
    - ./data/redmine/files:/usr/src/redmine/files
    - ./data/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
  depends_on:
    - redmine-db


redmine-db:
  image: mariadb
  container_name: redmine-db
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=***
    - MYSQL_DATABASE=redmine
  volumes:
    - ./data/redmine-db:/var/lib/mysql

```

In real-live it's more complicated, coz there is some reverse proxy (nginx), letsencrypt and other stuff :)
