### ISSUE TITLE
redmine/files directory is emtpy after docker-compose down

### ISSUE THREAD

**Issue by peektoseen** [docker-library/redmine#83]
Hi! First of all - thank you very much for this docker-library :+1: 
And my issue:
Here is my docker-compose.yml :
```
version: "3"
services:
  redmine:
    image: redmine
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      VIRTUAL_HOST: myhost.ru
    depends_on:
      - db
        #    restart: always
    networks:
      - myhost
    volumes:
      - ./redmine:/usr/src/redmine
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
      #    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - myhost
networks: 
  myhost:
    driver: bridge
```

After `docker-compose up` - redmine work fine, then i add few files in redmine. If I ssh to docker container and cd to /usr/src/redmine/files - I will see this files here. But files not added to "files" directory on host.
And after `docker-compose down` files will lost. 
How can I store 'files' directory on host?
