### ISSUE TITLE
Error resolving dependencies

### ISSUE THREAD

**Issue by aashmelev** [docker-library/redmine#96]
Dockerfile:
```
FROM redmine:3.4
RUN apt-get update -qq && apt-get install -y libffi-dev ruby-dev clang make gcc libmysqlclient-dev
WORKDIR /usr/src/redmine
COPY plugins plugins
COPY rgloader rgloader
```

docker-compose.yml:
```
version: '3.1'

networks:
  redmine-network:

services:

  redmine:
    build: .
    networks:
      - redmine-network
    volumes:
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/public/themes
      - ./files:/usr/src/redmine/files

    depends_on:
      - db
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: password

  db:
    image: mysql:5.7
    networks:
      - redmine-network
    restart: always
    command: ['mysqld', '--character-set-server=utf8']
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
```

The container load is interrupted on resolving dependencies:
> redmine_1  | Resolving dependencies...
> redmine_1  | Bundler could not find compatible versions for gem "axlsx":
> redmine_1  |   In Gemfile:
> redmine_1  |     axlsx (>= 2.0.1)
> redmine_1  |
> redmine_1  | Could not find gem 'axlsx (>= 2.0.1)' in any of the sources.
> redmine_1  |
> redmine_1  | Bundler could not find compatible versions for gem "rubyzip":
> redmine_1  |   In snapshot (Gemfile.lock):
> redmine_1  |     rubyzip (= 1.2.1)
> redmine_1  |
> redmine_1  |   In Gemfile:
> redmine_1  |     rubyzip (>= 1.0.0)
> redmine_1  |
> redmine_1  |     axlsx (>= 2.0.1) was resolved to 2.0.1, which depends on
> redmine_1  |       rubyzip (\~> 1.0.0)
> redmine_1  |
> redmine_1  |     selenium-webdriver (\~> 2.53.4) was resolved to 2.53.4, which depends on
> redmine_1  |       rubyzip (\~> 1.0)
> redmine_1  |
> redmine_1  | Running `bundle update` will rebuild your snapshot from scratch, using only
> redmine_1  | the gems in your Gemfile, which may resolve the conflict.

Run "bundle update" command doesn't help, because the error is returned after restart of the container.

_Sorry for my English._
